/**
 * MLEnhancer — Compleo v7.0 ML Layer
 *
 * Orchestrateur de la couche ML. Point d'entrée unique pour :
 *   - Améliorer le code généré par les règles via LLM + RAG
 *   - Indexer des exemples de migration réussis
 *
 * Le ML est optionnel et désactivé par défaut.
 * Si Ollama/ChromaDB ne sont pas disponibles, le code rule-based
 * est retourné sans modification.
 *
 * Usage :
 *   const enhancer = new MLEnhancer({ enabled: true, ... });
 *   await enhancer.initialize();
 *   const { code, source } = await enhancer.enhance(ejb, rules, ...);
 */

import { EmbeddingService } from "./embedding-service";
import { GenerationService } from "./generation-service";

// ── Types ────────────────────────────────────────────────────────

export interface MLConfig {
  enabled:        boolean;
  ollamaUrl:      string;
  chromaUrl:      string;
  model?:         string;
  minConfidence?: number;
}

export interface EnhanceResult {
  code:   string;
  source: "ml" | "rules";
}

// ── Enhancer ─────────────────────────────────────────────────────

export class MLEnhancer {
  private embedding:     EmbeddingService;
  private generation:    GenerationService;
  private _enabled:      boolean;
  private minConfidence: number;

  constructor(config: MLConfig) {
    this._enabled      = config.enabled;
    this.minConfidence = config.minConfidence ?? 0.6;
    this.embedding     = new EmbeddingService(
      config.chromaUrl, config.ollamaUrl
    );
    this.generation    = new GenerationService(
      config.ollamaUrl, config.model
    );
  }

  /**
   * Initialize the ML services (ChromaDB connection).
   * If initialization fails, ML is disabled gracefully.
   */
  async initialize(): Promise<void> {
    if (!this._enabled) return;
    try {
      await this.embedding.initialize();
      console.log("ML Enhancer prêt");
    } catch (e) {
      console.warn(`ML Enhancer init échoué (Ollama dispo ?): ${e}`);
      this._enabled = false;
    }
  }

  /**
   * Check if ML enhancement is enabled and ready.
   */
  get enabled(): boolean {
    return this._enabled;
  }

  /**
   * Enhance rule-based code using LLM + RAG.
   *
   * If ML is disabled or unavailable, returns the rule-based code unchanged.
   *
   * @param ejbCode     - Original EJB source code
   * @param ruleCode    - Code generated by the rule engine
   * @param methodName  - Method name for validation
   * @param voInType    - Input VO type (nullable)
   * @param voOutType   - Output VO type (nullable)
   * @returns Enhanced code and its source ("ml" or "rules")
   */
  async enhance(
    ejbCode:    string,
    ruleCode:   string,
    methodName: string,
    voInType:   string | null,
    voOutType:  string | null
  ): Promise<EnhanceResult> {

    // ML désactivé ou non disponible → retourner le rule-based
    if (!this._enabled) {
      return { code: ruleCode, source: "rules" };
    }

    try {
      // 1. Chercher des exemples similaires via RAG
      const similar = await this.embedding.findSimilar(ejbCode, 3);

      // 2. Améliorer avec le LLM
      const result = await this.generation.improveServiceMethod(
        ejbCode, ruleCode, similar,
        methodName, voInType, voOutType
      );

      if (result.warnings.length > 0) {
        console.warn(`ML warnings [${methodName}]:`, result.warnings);
      }

      // 3. Retourner ML si confiance suffisante, sinon rule-based
      return result.confidence >= this.minConfidence
        ? { code: result.code,  source: "ml" }
        : { code: ruleCode,     source: "rules" };

    } catch (e) {
      console.warn(`ML enhance failed [${methodName}]: ${e}`);
      return { code: ruleCode, source: "rules" };
    }
  }

  /**
   * Index a successful migration example for future RAG retrieval.
   *
   * @param ejbCode    - Original EJB source code
   * @param springCode - Successfully generated Spring Boot code
   * @param meta       - Metadata about the migration
   */
  async indexExample(
    ejbCode:    string,
    springCode: string,
    meta: {
      className:  string;
      methodName: string;
      javaType:   string;
      hasOracle:  boolean;
      hasJms:     boolean;
    }
  ): Promise<void> {
    if (!this._enabled) return;
    try {
      await this.embedding.indexPair({
        id:         `${meta.className}-${meta.methodName}`,
        ejbCode,
        springCode,
        meta,
      });
    } catch (e) {
      console.warn("Index example failed:", e);
    }
  }
}
