/**
 * StubRePromptEngine v13.18 — Re-prompt LLM forcé pour les méthodes stub.
 *
 * Prend les méthodes annotées @CompleoUnvalidated(severity="STUB") et injecte
 * un bloc commenté MIGRATED LOGIC contenant une traduction best-effort
 * du code legacy source.
 *
 * Le stub reste actif (throw CompleoUnvalidatedMethodException) mais le développeur
 * dispose d'un guide de migration directement dans le code.
 *
 * Utilise le prompt variant E (domain keywords) — gagnant de l'expérimentation v13.9.
 * v13.18: Traitement parallèle par batch de 5 pour réduire la durée.
 *
 * @author Compleo
 * @since v13.9
 */

import { llmGenerateCode, isLLMAvailable } from "../ml/llm-adapter";

// ─── Types ─────────────────────────────────────────────────────────────────────

export interface StubMethod {
  /** Nom de la méthode */
  methodName: string;
  /** Nom de la classe contenant le stub */
  className: string;
  /** Référence legacy (ex: "CreditJockerWebService.getLigneDeclicGAB") */
  legacyRef: string;
  /** Code source legacy (si disponible) */
  legacyBody?: string;
  /** Signature du stub (public ReturnType methodName(...)) */
  stubSignature: string;
}

export interface RePromptResult {
  /** Nombre de stubs traités */
  totalStubs: number;
  /** Nombre de stubs enrichis avec MIGRATED LOGIC */
  enrichedCount: number;
  /** Nombre de stubs non enrichis (LLM indisponible ou échec) */
  skippedCount: number;
  /** Détails par méthode */
  details: Array<{
    methodName: string;
    className: string;
    enriched: boolean;
    reason?: string;
  }>;
}

// ─── Domain Vocabulary (Variant E) ─────────────────────────────────────────────

const DOMAIN_VOCABULARY = `## Domain Vocabulary
- DECLIC: Credit line management system (système de gestion des lignes de crédit)
- GAB: ATM channel (Guichet Automatique Bancaire)
- TPE: POS terminal channel (Terminal de Paiement Électronique)
- Tirage: Credit drawdown (utilisation d'une ligne de crédit)
- Dossier (noDoss): Credit file/case number
- Solde: Balance
- Encours: Outstanding amount
- Impayés: Unpaid installments
- Avis Opéré: Transaction notification document
- RepDemat: Dematerialized response (réponse dématérialisée)
- Docubase: Document management system (GED)
- Flux: XML message envelope (legacy messaging format)
- Envelope: Legacy XML message wrapper
- Services.find(): Legacy UDDI service lookup (replaced by Spring DI)
- Parser.unmarshall/marshall: Legacy XML serialization (replaced by DTOs)`;

// ─── Prompt Builder (Variant E) ────────────────────────────────────────────────

function buildRePrompt(legacyCode: string, stubSignature: string, legacyRef: string): string {
  return `You are migrating a Moroccan banking legacy system (BOA Group / BMCE Bank) from EJB/SOAP to Spring Boot 3.x.

${DOMAIN_VOCABULARY}

## Legacy Code
\`\`\`java
${legacyCode}
\`\`\`

## Target Stub
\`\`\`java
${stubSignature}
\`\`\`

## Instructions
1. Translate to Spring Boot 3.x preserving ALL business logic
2. Use the domain vocabulary above to generate meaningful variable names
3. Replace legacy framework calls with Spring equivalents
4. Preserve error codes and business validation rules exactly
5. Add // TODO: [VERIFY] for parts requiring human review
6. Wrap output in: /* MIGRATED LOGIC — from ${legacyRef} */

Output ONLY the method body (Java code). No markdown fences.`;
}

// ─── Output Cleanup ────────────────────────────────────────────────────────────

function cleanLLMOutput(raw: string): string {
  let cleaned = raw.trim();
  // Remove markdown fences
  cleaned = cleaned.replace(/^```java\s*\n?/gm, "").replace(/\n?```\s*$/gm, "");
  cleaned = cleaned.replace(/^```\s*\n?/gm, "");
  // Ensure it starts with /* MIGRATED LOGIC
  if (!cleaned.startsWith("/*")) {
    cleaned = `/* MIGRATED LOGIC — best-effort translation */\n${cleaned}`;
  }
  return cleaned;
}

function wrapAsComment(code: string, legacyRef: string): string {
  // Use // comments to avoid nested /* */ which breaks Java compilation
  const lines = code.split("\n");
  // Strip any /* */ from the LLM output to prevent nested block comments
  const sanitizedLines = lines.map(line => line.replace(/\/\*/g, "//").replace(/\*\//g, "//"));
  const commentLines = sanitizedLines.map(line => `    // ${line}`);
  return [
    `    // ─── MIGRATED LOGIC (best-effort) ───────────────────────────────────`,
    `    // Source: ${legacyRef}`,
    `    // Generated by Compleo v13.9 Re-prompt Engine`,
    `    // Status: UNVALIDATED — requires human review`,
    `    //`,
    ...commentLines,
    `    //`,
    `    // ─── END MIGRATED LOGIC ─────────────────────────────────────────────`,
  ].join("\n");
}

// ─── File Scanner ──────────────────────────────────────────────────────────────

/**
 * Extrait les méthodes stub d'un fichier Java.
 */
function extractStubMethods(filePath: string, content: string): StubMethod[] {
  const stubs: StubMethod[] = [];
  const classNameMatch = filePath.match(/([A-Z]\w+)\.java$/);
  const className = classNameMatch ? classNameMatch[1] : "Unknown";

  // Pattern: @CompleoUnvalidated(...) + method with CompleoUnvalidatedMethodException
  const pattern = /@CompleoUnvalidated\(severity\s*=\s*"STUB",\s*legacyRef\s*=\s*"([^"]+)"[^)]*\)\s*\n\s*((?:@\w+[^\n]*\n\s*)*(?:public|protected)\s+\S+\s+(\w+)\s*\([^)]*\)\s*\{[^}]*CompleoUnvalidatedMethodException[^}]*\})/g;

  let match;
  while ((match = pattern.exec(content)) !== null) {
    stubs.push({
      methodName: match[3],
      className,
      legacyRef: match[1],
      stubSignature: match[2],
    });
  }

  return stubs;
}

/**
 * Cherche le code legacy source correspondant à un legacyRef dans les fichiers source.
 */
function findLegacyBody(legacyRef: string, sourceFiles: Array<{ path: string; content: string }>): string | undefined {
  const [className, methodName] = legacyRef.split(".");
  if (!className || !methodName) return undefined;

  // Build candidate class names for fuzzy matching
  // e.g., "AvisOpereGetListIndexService" -> also try "AvisOpereGetListIndexUC", "AvisOpereGetListIndex"
  const candidates = [className];
  const SUFFIXES_TO_STRIP = ["Service", "Impl", "Controller", "Bean", "WS", "Delegate"];
  const SUFFIXES_TO_TRY = ["UC", "Bean", "WS", "Impl", "Action", "Servlet", "Helper"];
  for (const suffix of SUFFIXES_TO_STRIP) {
    if (className.endsWith(suffix)) {
      const base = className.slice(0, -suffix.length);
      candidates.push(base);
      for (const trySuffix of SUFFIXES_TO_TRY) {
        candidates.push(base + trySuffix);
      }
    }
  }

  for (const file of sourceFiles) {
    if (!candidates.some(c => file.path.includes(c))) continue;

    // Extraire la méthode du fichier source
    // Note: [\s\S]*? dans les params pour supporter @WebParam(name="...") avec parenthèses
    const methodPattern = new RegExp(
      `(?:public|protected|private)\\s+\\S+\\s+${methodName}\\s*\\([\\s\\S]*?\\)\\s*(?:throws\\s+[^{]+)?\\{`,
      "g"
    );
    const methodMatch = methodPattern.exec(file.content);
    if (!methodMatch) continue;

    // Extraire le body complet (brace-balanced)
    const startIdx = methodMatch.index;
    let braceCount = 0;
    let endIdx = startIdx;
    let foundFirst = false;

    for (let i = startIdx; i < file.content.length; i++) {
      if (file.content[i] === "{") {
        braceCount++;
        foundFirst = true;
      } else if (file.content[i] === "}") {
        braceCount--;
        if (foundFirst && braceCount === 0) {
          endIdx = i + 1;
          break;
        }
      }
    }

    if (endIdx > startIdx) {
      return file.content.substring(startIdx, endIdx);
    }
  }

  return undefined;
}

// ─── Batch LLM Result Type ────────────────────────────────────────────────────

type StubLLMResult =
  | { enriched: false; stub: StubMethod; reason: string }
  | { enriched: true; stub: StubMethod; file: { path: string; content: string }; commentBlock: string };

// ─── Main Engine ───────────────────────────────────────────────────────────────

/** v13.18: Concurrency batch size for parallel LLM calls */
const LLM_BATCH_SIZE = 5;

export class StubRePromptEngine {
  private maxMethodsPerRun: number;
  private maxBodyLOC: number;

  constructor(options?: { maxMethodsPerRun?: number; maxBodyLOC?: number }) {
    this.maxMethodsPerRun = options?.maxMethodsPerRun ?? 20;
    this.maxBodyLOC = options?.maxBodyLOC ?? 100;
  }

  /**
   * Traite les fichiers générés pour enrichir les stubs avec MIGRATED LOGIC.
   * v13.18: Traitement parallèle par batch de LLM_BATCH_SIZE.
   */
  async process(
    generatedFiles: Array<{ path: string; content: string }>,
    sourceFiles: Array<{ path: string; content: string }>,
  ): Promise<RePromptResult> {
    const result: RePromptResult = {
      totalStubs: 0,
      enrichedCount: 0,
      skippedCount: 0,
      details: [],
    };

    // 1. Vérifier disponibilité LLM
    const llmAvailable = await isLLMAvailable();
    if (!llmAvailable) {
      // Scan stubs for counting only
      for (const file of generatedFiles) {
        const stubs = extractStubMethods(file.path, file.content);
        result.totalStubs += stubs.length;
        result.skippedCount += stubs.length;
        for (const stub of stubs) {
          result.details.push({
            methodName: stub.methodName,
            className: stub.className,
            enriched: false,
            reason: "LLM unavailable",
          });
        }
      }
      return result;
    }

    // 2. Collecter tous les stubs
    const allStubs: Array<{ file: typeof generatedFiles[0]; stub: StubMethod }> = [];
    for (const file of generatedFiles) {
      if (!file.path.endsWith(".java")) continue;
      if (file.path.includes("CompleoUnvalidated")) continue; // Skip annotation files
      const stubs = extractStubMethods(file.path, file.content);
      for (const stub of stubs) {
        allStubs.push({ file, stub });
      }
    }

    result.totalStubs = allStubs.length;

    // 3. Limiter le nombre de méthodes par run
    const toProcess = allStubs.slice(0, this.maxMethodsPerRun);

    // 4. v13.18: Traiter par batch parallèle de LLM_BATCH_SIZE
    for (let i = 0; i < toProcess.length; i += LLM_BATCH_SIZE) {
      const batch = toProcess.slice(i, i + LLM_BATCH_SIZE);

      // Phase A: Appels LLM en parallèle (I/O-bound, safe to parallelize)
      const batchResults = await Promise.allSettled(
        batch.map(({ file, stub }) => this.processOneStub(file, stub, sourceFiles)),
      );

      // Phase B: Appliquer les mutations de fichier séquentiellement
      // (les insertions dans file.content doivent être ordonnées pour éviter les décalages)
      for (const settled of batchResults) {
        if (settled.status === "rejected") {
          result.skippedCount++;
          result.details.push({
            methodName: "unknown",
            className: "unknown",
            enriched: false,
            reason: `LLM error: ${settled.reason instanceof Error ? settled.reason.message : String(settled.reason)}`,
          });
          continue;
        }

        const r = settled.value;
        if (!r.enriched) {
          result.skippedCount++;
          result.details.push({
            methodName: r.stub.methodName,
            className: r.stub.className,
            enriched: false,
            reason: r.reason,
          });
          continue;
        }

        // Injecter le commentaire AVANT le @CompleoUnvalidated
        const annotationPattern = new RegExp(
          `([ \\t]*)@CompleoUnvalidated\\(severity\\s*=\\s*"STUB",\\s*legacyRef\\s*=\\s*"${r.stub.legacyRef.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}"`,
        );
        const annotMatch = annotationPattern.exec(r.file.content);
        if (annotMatch) {
          const insertPos = annotMatch.index;
          r.file.content = r.file.content.substring(0, insertPos) +
            r.commentBlock + "\n" +
            r.file.content.substring(insertPos);

          result.enrichedCount++;
          result.details.push({
            methodName: r.stub.methodName,
            className: r.stub.className,
            enriched: true,
          });
        } else {
          result.skippedCount++;
          result.details.push({
            methodName: r.stub.methodName,
            className: r.stub.className,
            enriched: false,
            reason: "Could not locate annotation insertion point",
          });
        }
      }
    }

    // Stubs au-delà de maxMethodsPerRun
    const remaining = allStubs.length - toProcess.length;
    if (remaining > 0) {
      result.skippedCount += remaining;
    }

    return result;
  }

  /**
   * Traite un seul stub : validation + appel LLM.
   * Retourne un résultat typé sans muter le fichier (mutation faite dans la boucle appelante).
   */
  private async processOneStub(
    file: { path: string; content: string },
    stub: StubMethod,
    sourceFiles: Array<{ path: string; content: string }>,
  ): Promise<StubLLMResult> {
    // Chercher le code legacy source
    const legacyBody = stub.legacyBody || findLegacyBody(stub.legacyRef, sourceFiles);
    if (!legacyBody) {
      return { enriched: false, stub, reason: "Legacy source not found" };
    }

    // Vérifier la taille
    const bodyLOC = legacyBody.split("\n").filter(l => l.trim()).length;
    if (bodyLOC > this.maxBodyLOC) {
      return { enriched: false, stub, reason: `Body too large (${bodyLOC} LOC > ${this.maxBodyLOC})` };
    }

    // Appeler le LLM
    const prompt = buildRePrompt(legacyBody, stub.stubSignature, stub.legacyRef);
    const generated = await llmGenerateCode(prompt, {
      temperature: 0.2,
      maxTokens: 3000,
    });

    if (!generated || generated.trim().length < 20) {
      return { enriched: false, stub, reason: "LLM returned empty/short response" };
    }

    // Nettoyer et envelopper comme commentaire
    const cleaned = cleanLLMOutput(generated);
    const commentBlock = wrapAsComment(cleaned, stub.legacyRef);

    return { enriched: true, stub, file, commentBlock };
  }
}
