/**
 * Tests unitaires — StubRePromptEngine v13.9
 */
import { describe, it, expect, vi, beforeEach } from "vitest";

// Mock the LLM adapter
vi.mock("../ml/llm-adapter", () => ({
  isLLMAvailable: vi.fn(),
  llmGenerateCode: vi.fn(),
}));

import { StubRePromptEngine } from "./StubRePromptEngine";
import { isLLMAvailable, llmGenerateCode } from "../ml/llm-adapter";

const mockedIsLLMAvailable = vi.mocked(isLLMAvailable);
const mockedLlmGenerateCode = vi.mocked(llmGenerateCode);

describe("StubRePromptEngine v13.9", () => {
  let engine: StubRePromptEngine;

  beforeEach(() => {
    vi.clearAllMocks();
    engine = new StubRePromptEngine({ maxMethodsPerRun: 10, maxBodyLOC: 100 });
  });

  const STUB_FILE = {
    path: "src/main/java/com/app/service/CreditService.java",
    content: `package com.app.service;

import com.app.common.CompleoUnvalidated;
import com.app.common.CompleoUnvalidatedMethodException;

public class CreditService {

    @CompleoUnvalidated(severity = "STUB", legacyRef = "CreditJockerWebService.getLigneDeclicGAB", migrationDate = "2026-05-12")
    public String getLigneDeclicGAB(String accountNumber, String channel) {
        throw new CompleoUnvalidatedMethodException("getLigneDeclicGAB", "CreditJockerWebService.getLigneDeclicGAB", "STUB");
    }

    @CompleoUnvalidated(severity = "STUB", legacyRef = "CreditJockerWebService.BlocageJoker", migrationDate = "2026-05-12")
    public String BlocageJoker(String flux) {
        throw new CompleoUnvalidatedMethodException("BlocageJoker", "CreditJockerWebService.BlocageJoker", "STUB");
    }
}`,
  };

  const LEGACY_FILE = {
    path: "src/CreditJockerWebService.java",
    content: `public class CreditJockerWebService {
    public String getLigneDeclicGAB(String accountNumber, String channel) {
        String result = "";
        try {
            Envelope env = Parser.unmarshall(accountNumber);
            String code = env.getNodeAsString("code");
            if ("000".equals(code)) {
                result = env.getNodeAsString("ligne");
            }
        } catch (Exception e) {
            Log.error("Erreur getLigneDeclicGAB", e);
        }
        return result;
    }

    public String BlocageJoker(String flux) {
        String reponse = "";
        try {
            SynchroneService svc = (SynchroneService) Services.find("BlocageJoker", SynchroneService.class);
            reponse = svc.execute(flux);
        } catch (Exception e) {
            Log.error("Erreur BlocageJoker", e);
        }
        return reponse;
    }
}`,
  };

  it("should return early when LLM is unavailable", async () => {
    mockedIsLLMAvailable.mockResolvedValue(false);

    const result = await engine.process([STUB_FILE], [LEGACY_FILE]);

    expect(result.totalStubs).toBe(2);
    expect(result.enrichedCount).toBe(0);
    expect(result.skippedCount).toBe(2);
    expect(result.details[0].reason).toBe("LLM unavailable");
  });

  it("should enrich stubs when LLM is available and legacy source found", async () => {
    mockedIsLLMAvailable.mockResolvedValue(true);
    mockedLlmGenerateCode.mockResolvedValue(
      `/* MIGRATED LOGIC — from CreditJockerWebService.getLigneDeclicGAB */
String result = "";
try {
    // TODO: [VERIFY] Replace with DTO getter
    String code = response.getCode();
    if ("000".equals(code)) {
        result = response.getLigne();
    }
} catch (Exception e) {
    log.error("Erreur getLigneDeclicGAB", e);
}
return result;
/* END MIGRATED LOGIC */`
    );

    const files = [{ ...STUB_FILE }]; // Clone to avoid mutation issues
    const result = await engine.process(files, [LEGACY_FILE]);

    expect(result.totalStubs).toBe(2);
    expect(result.enrichedCount).toBe(2);
    expect(result.skippedCount).toBe(0);

    // Verify the MIGRATED LOGIC comment was injected (// format)
    expect(files[0].content).toContain("// ─── MIGRATED LOGIC (best-effort)");
    expect(files[0].content).toContain("// Source: CreditJockerWebService.getLigneDeclicGAB");
    expect(files[0].content).toContain("// Generated by Compleo v13.9");
    expect(files[0].content).toContain("// ─── END MIGRATED LOGIC");

    // Verify the stub is still active (throw is preserved)
    expect(files[0].content).toContain("throw new CompleoUnvalidatedMethodException");
  });

  it("should skip methods when legacy source is not found", async () => {
    mockedIsLLMAvailable.mockResolvedValue(true);

    const result = await engine.process([STUB_FILE], []); // No source files

    expect(result.totalStubs).toBe(2);
    expect(result.enrichedCount).toBe(0);
    expect(result.skippedCount).toBe(2);
    expect(result.details[0].reason).toBe("Legacy source not found");
  });

  it("should skip methods with body too large", async () => {
    mockedIsLLMAvailable.mockResolvedValue(true);

    // Create a legacy file with a very long method
    const longBody = Array(200).fill("    String x = \"line\";").join("\n");
    const longLegacyFile = {
      path: "src/CreditJockerWebService.java",
      content: `public class CreditJockerWebService {
    public String getLigneDeclicGAB(String accountNumber, String channel) {
${longBody}
        return "";
    }
}`,
    };

    const smallEngine = new StubRePromptEngine({ maxMethodsPerRun: 10, maxBodyLOC: 50 });
    const result = await smallEngine.process([STUB_FILE], [longLegacyFile]);

    // getLigneDeclicGAB should be skipped (too large), BlocageJoker not found
    const getLigneDetail = result.details.find(d => d.methodName === "getLigneDeclicGAB");
    expect(getLigneDetail?.enriched).toBe(false);
    expect(getLigneDetail?.reason).toContain("Body too large");
  });

  it("should handle LLM errors gracefully", async () => {
    mockedIsLLMAvailable.mockResolvedValue(true);
    mockedLlmGenerateCode.mockRejectedValue(new Error("LLM timeout"));

    const result = await engine.process([STUB_FILE], [LEGACY_FILE]);

    expect(result.totalStubs).toBe(2);
    expect(result.enrichedCount).toBe(0);
    expect(result.skippedCount).toBe(2);
    expect(result.details[0].reason).toContain("LLM error");
  });

  it("should respect maxMethodsPerRun limit", async () => {
    mockedIsLLMAvailable.mockResolvedValue(true);
    mockedLlmGenerateCode.mockResolvedValue("// migrated code\nreturn result;");

    const limitedEngine = new StubRePromptEngine({ maxMethodsPerRun: 1, maxBodyLOC: 100 });
    const result = await limitedEngine.process([STUB_FILE], [LEGACY_FILE]);

    // Only 1 method should be processed, the other skipped
    expect(result.enrichedCount + result.skippedCount).toBeLessThanOrEqual(2);
    expect(mockedLlmGenerateCode).toHaveBeenCalledTimes(1);
  });

  it("should not modify files without @CompleoUnvalidated stubs", async () => {
    mockedIsLLMAvailable.mockResolvedValue(true);

    const cleanFile = {
      path: "src/main/java/com/app/service/HealthService.java",
      content: `package com.app.service;
public class HealthService {
    public String health() { return "OK"; }
}`,
    };

    const result = await engine.process([cleanFile], [LEGACY_FILE]);

    expect(result.totalStubs).toBe(0);
    expect(result.enrichedCount).toBe(0);
  });
});
