/**
 * Spring Boot Code Generator — Orchestrator.
 * Delegates to sub-generators in server/spring/ for each concern.
 *
 * Implements 12 senior-developer quality rules (R1–R12).
 *
 * v5.5: Refactored from 2200-line monolith into 8 focused modules.
 *
 * @author Hamza NORDINE
 */

import type {
  ProjectIR, UseCaseIR, DtoIR, DtoFieldIR, ServiceIR,
  EnumIR, ExceptionIR, ValidatorIR, RemoteInterfaceIR,
} from "./java-parser";

// ─── Re-export types from shared (backward compatibility) ───────────────────
export type {
  GeneratedFile, GenerationResult, GenerationStats,
  CompilationResult, CompilationError, MigrationReportContext,
} from "./spring/shared";

import type { GeneratedFile, GenerationResult, GenerationStats, CompilationResult, CompilationError, MigrationReportContext } from "./spring/shared";

// ─── Import sub-generators ──────────────────────────────────────────────────
import { generateDto } from "./spring/dto-gen";
import { generateEnum, generateException, generateGlobalExceptionHandler, generateValidator } from "./spring/model-gen";
import { generateDomainService } from "./spring/service-gen";
import { generateDomainController } from "./spring/controller-gen";
import { generateDomainControllerTest } from "./spring/test-gen";
import {
  generateMainApplication,
  generateRemoteServiceAdapter,
  generateInjectedServiceStub,
  generateApplicationYml,
  generateApplicationProperties,
  generateDockerfile,
  generateDockerCompose,
  generateK8sDeployment,
  generateK8sService,
  generatePomXml,
  generateMigrationReport,
} from "./spring/infra-gen";

// ─── Main Generator (Orchestrator) ──────────────────────────────────────────

export function generateSpringBootProject(ir: ProjectIR, reportContext?: MigrationReportContext): GenerationResult {
  const files: GeneratedFile[] = [];
  const warnings: string[] = [];

  const basePackage = ir.groupId ? `${ir.groupId}.${ir.artifactId.replace(/-/g, "")}` : "com.example.app";
  const basePath = `src/main/java/${basePackage.replace(/\./g, "/")}`;
  const testPath = `src/test/java/${basePackage.replace(/\./g, "/")}`;

  // Group UseCases by domain
  const domainMap = new Map<string, UseCaseIR[]>();
  for (const uc of ir.useCases) {
    const domain = uc.domain || "general";
    if (!domainMap.has(domain)) domainMap.set(domain, []);
    domainMap.get(domain)!.push(uc);
  }

  // Build DTO lookup
  const dtoMap = new Map<string, DtoIR>();
  for (const dto of ir.dtos) {
    dtoMap.set(dto.className, dto);
  }

  // 1. Generate Main Application
  files.push(generateMainApplication(basePackage, basePath, ir));

  // 2. Generate DTOs (Request/Response) — R9, R10
  for (const dto of ir.dtos) {
    files.push(generateDto(basePackage, basePath, dto, ir.enums));
  }

  // 3. Generate Enums
  for (const en of ir.enums) {
    files.push(generateEnum(basePackage, basePath, en));
  }

  // 4. Generate Exceptions
  for (const ex of ir.exceptions) {
    files.push(generateException(basePackage, basePath, ex));
  }
  // Always generate GlobalExceptionHandler — R3
  files.push(generateGlobalExceptionHandler(basePackage, basePath, ir.exceptions));

  // CORRECTION v5.2: Always generate BusinessRuleException for test coherence
  files.push({
    path: `${basePath}/exception/BusinessRuleException.java`,
    category: "exception" as const,
    content: `package ${basePackage}.exception;

/**
 * BusinessRuleException — thrown when a business rule is violated.
 * Handled by GlobalExceptionHandler → HTTP 422 Unprocessable Entity.
 * Auto-generated by Compleo Modernizer.
 */
public class BusinessRuleException extends RuntimeException {

    public BusinessRuleException(String message) {
        super(message);
    }

    public BusinessRuleException(String message, Throwable cause) {
        super(message, cause);
    }
}
`,
  });

  // 5. Generate Validators
  for (const val of ir.validators) {
    files.push(generateValidator(basePackage, basePath, val));
  }

  // 6. Generate Services (one per domain) — R6, R7, R8
  for (const [domain, useCases] of domainMap) {
    files.push(generateDomainService(basePackage, basePath, domain, useCases, dtoMap, ir));
  }

  // 7. Generate Controllers (one per domain) — R1, R2, R3, R4, R5
  for (const [domain, useCases] of domainMap) {
    files.push(generateDomainController(basePackage, basePath, domain, useCases, dtoMap));
  }

  // 8. Generate Tests (one per controller) — R11, R12
  for (const [domain, useCases] of domainMap) {
    files.push(generateDomainControllerTest(basePackage, testPath, domain, useCases, dtoMap));
  }

  // 9. Generate Remote Service adapters — R8
  for (const remote of ir.remoteInterfaces) {
    files.push(generateRemoteServiceAdapter(basePackage, basePath, remote));
  }

  // CORRECTION v5.2: Generate stub adapters for injected services not covered by @Remote interfaces
  const remoteTypeNames = new Set(ir.remoteInterfaces.map(r => r.className));
  const injectedServiceTypes = new Set<string>();
  for (const uc of ir.useCases) {
    for (const svc of uc.injectedServices) {
      if (!remoteTypeNames.has(svc.type) && !svc.type.endsWith("DAO") && !svc.type.endsWith("Repository")) {
        injectedServiceTypes.add(svc.type);
      }
    }
  }
  for (const svcType of injectedServiceTypes) {
    const sourceFile = (ir as any)._rawFiles?.find((f: any) => f.className === svcType);
    if (sourceFile) {
      files.push(generateInjectedServiceStub(basePackage, basePath, svcType, sourceFile.content));
    } else {
      files.push(generateInjectedServiceStub(basePackage, basePath, svcType, ""));
    }
  }

  // 10. Generate Config files
  files.push(generateApplicationYml(ir));
  files.push(generateApplicationProperties(ir));

  // 11. Generate Cloud files
  files.push(generateDockerfile(ir));
  files.push(generateDockerCompose(ir));
  files.push(generateK8sDeployment(ir));
  files.push(generateK8sService(ir));

  // 12. Generate pom.xml
  files.push(generatePomXml(ir, basePackage));

  // 13. Generate Migration Report (enriched with ambiguity context)
  files.push(generateMigrationReport(ir, domainMap, dtoMap, reportContext));

  // Compute stats
  const stats: GenerationStats = {
    totalFiles: files.length,
    controllers: files.filter(f => f.category === "controller").length,
    services: files.filter(f => f.category === "service").length,
    dtos: files.filter(f => f.category === "dto").length,
    tests: files.filter(f => f.category === "test").length,
    enums: files.filter(f => f.category === "enum").length,
    exceptions: files.filter(f => f.category === "exception").length,
    validators: files.filter(f => f.category === "validator").length,
    configFiles: files.filter(f => f.category === "config").length,
    cloudFiles: files.filter(f => f.category === "cloud").length,
    totalLinesGenerated: files.reduce((sum, f) => sum + f.content.split("\n").length, 0),
  };

  // Step 4.2 — Syntax verification
  const compilationResult = verifySyntax(files);

  return { files, stats, warnings, compilationResult };
}

// ─── Step 4.2: Syntax Verification ─────────────────────────────────────────

export function verifySyntax(files: GeneratedFile[]): CompilationResult {
  const errors: CompilationError[] = [];
  const javaFiles = files.filter(f => f.path.endsWith(".java"));
  let passedFiles = 0;

  for (const file of javaFiles) {
    const fileErrors = verifyJavaFile(file);
    if (fileErrors.length === 0) {
      passedFiles++;
    } else {
      errors.push(...fileErrors);
    }
  }

  return {
    status: errors.some(e => e.severity === "error") ? "ERRORS" : errors.length > 0 ? "WARNINGS" : "OK",
    errors,
    checkedFiles: javaFiles.length,
    passedFiles,
  };
}

function verifyJavaFile(file: GeneratedFile): CompilationError[] {
  const errors: CompilationError[] = [];
  const lines = file.content.split("\n");
  const fileName = file.path.split("/").pop() || file.path;

  // 1. Check brace balance
  let braceCount = 0;
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const cleaned = line.replace(/"[^"]*"/g, "").replace(/\/\/.*$/, "");
    for (const ch of cleaned) {
      if (ch === "{") braceCount++;
      if (ch === "}") braceCount--;
    }
    if (braceCount < 0) {
      errors.push({ file: fileName, line: i + 1, column: 0, message: "Unexpected closing brace", severity: "error" });
    }
  }
  if (braceCount !== 0) {
    errors.push({ file: fileName, line: lines.length, column: 0, message: `Unbalanced braces: ${braceCount > 0 ? "missing" : "extra"} ${Math.abs(braceCount)} closing brace(s)`, severity: "error" });
  }

  // 2. Check package declaration
  if (!file.content.match(/^package\s+[\w.]+;/m) && file.path.endsWith(".java") && !file.path.includes("module-info")) {
    errors.push({ file: fileName, line: 1, column: 0, message: "Missing package declaration", severity: "error" });
  }

  // 3. Check for duplicate imports
  const importLines = lines.filter(l => l.trim().startsWith("import "));
  const importSet = new Set<string>();
  for (const imp of importLines) {
    const trimmed = imp.trim();
    if (importSet.has(trimmed)) {
      const lineNum = lines.indexOf(imp) + 1;
      errors.push({ file: fileName, line: lineNum, column: 0, message: `Duplicate import: ${trimmed}`, severity: "warning" });
    }
    importSet.add(trimmed);
  }

  // 4. Check for "Object" type usage (R9 violation)
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (line.trim().startsWith("//") || line.trim().startsWith("*") || line.trim().startsWith("/*")) continue;
    if (/\bObject\b/.test(line) && !line.includes("@Override") && !line.includes("Object...") && !line.includes("ObjectMapper")) {
      if (/private\s+Object\s+/.test(line) || /public\s+Object\s+/.test(line) || /\(Object\s+/.test(line)) {
        errors.push({ file: fileName, line: i + 1, column: 0, message: "R9 violation: 'Object' type used — should be a specific type", severity: "warning" });
      }
    }
  }

  // 5. Check for missing semicolons on declarations
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();
    if (!line) continue;
    if (line.startsWith("//") || line.startsWith("*") || line.startsWith("/*") || line.startsWith("@") || line.startsWith("package") || line.startsWith("import")) continue;
    if (line.endsWith("{") || line.endsWith("}") || line.endsWith(",") || line.endsWith("(") || line.endsWith(")")) continue;
    if (/^(private|public|protected)\s+\w+\s+\w+\s*=/.test(line) && !line.endsWith(";")) {
      errors.push({ file: fileName, line: i + 1, column: line.length, message: "Missing semicolon", severity: "error" });
    }
  }

  return errors;
}
