/**
 * Spring Boot Code Generator — Generates a complete Spring Boot 3.2 project
 * from the EJB Project IR (Intermediate Representation).
 *
 * Generates: Controllers, Services, DTOs, Tests, Enums, Exceptions,
 * Validators, Config, Cloud (Docker, K8s), pom.xml, application.yml,
 * and a MIGRATION_REPORT.md.
 *
 * Implements 12 senior-developer quality rules:
 *   R1  — Semantic endpoint naming
 *   R2  — PathVariable vs RequestBody
 *   R3  — Semantic HTTP status codes
 *   R4  — No try/catch in Controllers
 *   R5  — Javadoc → @Operation OpenAPI
 *   R6  — Constructor injection (Lombok @RequiredArgsConstructor)
 *   R7  — @Transactional at the right level
 *   R8  — Stub for external dependencies with Magix code
 *   R9  — Strict types, never Object
 *   R10 — Bean Validation from source annotations
 *   R11 — Realistic test data (given/when/then)
 *   R12 — Minimum 3 tests per endpoint
 *
 * @author Hamza NORDINE
 */

import type {
  ProjectIR, UseCaseIR, DtoIR, DtoFieldIR, ServiceIR,
  EnumIR, ExceptionIR, ValidatorIR, RemoteInterfaceIR,
} from "./java-parser";

export interface GeneratedFile {
  path: string;
  content: string;
  category: "controller" | "service" | "dto" | "test" | "enum" | "exception" |
    "validator" | "config" | "cloud" | "pom" | "report" | "main" | "other";
}

export interface GenerationResult {
  files: GeneratedFile[];
  stats: GenerationStats;
  warnings: string[];
  compilationResult?: CompilationResult;
}

export interface GenerationStats {
  totalFiles: number;
  controllers: number;
  services: number;
  dtos: number;
  tests: number;
  enums: number;
  exceptions: number;
  validators: number;
  configFiles: number;
  cloudFiles: number;
  totalLinesGenerated: number;
}

export interface CompilationResult {
  status: "OK" | "ERRORS" | "WARNINGS";
  errors: CompilationError[];
  checkedFiles: number;
  passedFiles: number;
}

export interface CompilationError {
  file: string;
  line: number;
  column: number;
  message: string;
  severity: "error" | "warning";
}

export interface MigrationReportContext {
  ambiguities?: Array<{
    id: string;
    type: string;
    severity: string;
    question: string;
    affectedClass: string;
    recommendation: string;
    recommendationReason: string;
    options: Array<{ id: string; label: string }>;
  }>;
  userChoices?: Array<{
    ambiguityId: string;
    selectedOptionId: string;
  }>;
  autoResolvedCount?: number;
  userResolvedCount?: number;
}

// ─── Main Generator ─────────────────────────────────────────────────────────

export function generateSpringBootProject(ir: ProjectIR, reportContext?: MigrationReportContext): GenerationResult {
  const files: GeneratedFile[] = [];
  const warnings: string[] = [];

  const basePackage = ir.groupId ? `${ir.groupId}.${ir.artifactId.replace(/-/g, "")}` : "com.example.app";
  const basePath = `src/main/java/${basePackage.replace(/\./g, "/")}`;
  const testPath = `src/test/java/${basePackage.replace(/\./g, "/")}`;

  // Group UseCases by domain
  const domainMap = new Map<string, UseCaseIR[]>();
  for (const uc of ir.useCases) {
    const domain = uc.domain || "general";
    if (!domainMap.has(domain)) domainMap.set(domain, []);
    domainMap.get(domain)!.push(uc);
  }

  // Build DTO lookup
  const dtoMap = new Map<string, DtoIR>();
  for (const dto of ir.dtos) {
    dtoMap.set(dto.className, dto);
  }

  // Build enum lookup
  const enumNames = new Set(ir.enums.map(e => e.className));

  // 1. Generate Main Application
  files.push(generateMainApplication(basePackage, basePath, ir));

  // 2. Generate DTOs (Request/Response) — R9, R10
  for (const dto of ir.dtos) {
    files.push(generateDto(basePackage, basePath, dto, ir.enums));
  }

  // 3. Generate Enums
  for (const en of ir.enums) {
    files.push(generateEnum(basePackage, basePath, en));
  }

  // 4. Generate Exceptions
  for (const ex of ir.exceptions) {
    files.push(generateException(basePackage, basePath, ex));
  }
  // Always generate GlobalExceptionHandler — R3
  files.push(generateGlobalExceptionHandler(basePackage, basePath, ir.exceptions));

  // CORRECTION v5.2: Always generate BusinessRuleException for test coherence
  files.push({
    path: `${basePath}/exception/BusinessRuleException.java`,
    category: "exception" as const,
    content: `package ${basePackage}.exception;

/**
 * BusinessRuleException — thrown when a business rule is violated.
 * Handled by GlobalExceptionHandler → HTTP 422 Unprocessable Entity.
 * Auto-generated by Compleo Modernizer.
 */
public class BusinessRuleException extends RuntimeException {

    public BusinessRuleException(String message) {
        super(message);
    }

    public BusinessRuleException(String message, Throwable cause) {
        super(message, cause);
    }
}
`,
  });

  // 5. Generate Validators
  for (const val of ir.validators) {
    files.push(generateValidator(basePackage, basePath, val));
  }

  // 6. Generate Services (one per domain) — R6, R7, R8
  for (const [domain, useCases] of domainMap) {
    files.push(generateDomainService(basePackage, basePath, domain, useCases, dtoMap, ir));
  }

  // 7. Generate Controllers (one per domain) — R1, R2, R3, R4, R5
  for (const [domain, useCases] of domainMap) {
    files.push(generateDomainController(basePackage, basePath, domain, useCases, dtoMap));
  }

  // 8. Generate Tests (one per controller) — R11, R12
  for (const [domain, useCases] of domainMap) {
    files.push(generateDomainControllerTest(basePackage, testPath, domain, useCases, dtoMap));
  }

  // 9. Generate Remote Service adapters — R8
  for (const remote of ir.remoteInterfaces) {
    files.push(generateRemoteServiceAdapter(basePackage, basePath, remote));
  }

  // CORRECTION v5.2: Generate stub adapters for injected services not covered by @Remote interfaces
  // (e.g., MagixService which is an interface without @Remote annotation)
  const remoteTypeNames = new Set(ir.remoteInterfaces.map(r => r.className));
  const injectedServiceTypes = new Set<string>();
  for (const uc of ir.useCases) {
    for (const svc of uc.injectedServices) {
      if (!remoteTypeNames.has(svc.type) && !svc.type.endsWith("DAO") && !svc.type.endsWith("Repository")) {
        injectedServiceTypes.add(svc.type);
      }
    }
  }
  // Find the source interface in _rawFiles to extract method signatures
  for (const svcType of injectedServiceTypes) {
    const sourceFile = (ir as any)._rawFiles?.find((f: any) => f.className === svcType);
    if (sourceFile) {
      files.push(generateInjectedServiceStub(basePackage, basePath, svcType, sourceFile.content));
    } else {
      // Generate a minimal stub even without source
      files.push(generateInjectedServiceStub(basePackage, basePath, svcType, ""));
    }
  }

  // 10. Generate Config files
  files.push(generateApplicationYml(ir));
  files.push(generateApplicationProperties(ir));

  // 11. Generate Cloud files
  files.push(generateDockerfile(ir));
  files.push(generateDockerCompose(ir));
  files.push(generateK8sDeployment(ir));
  files.push(generateK8sService(ir));

  // 12. Generate pom.xml
  files.push(generatePomXml(ir, basePackage));

  // 13. Generate Migration Report (enriched with ambiguity context)
  files.push(generateMigrationReport(ir, domainMap, dtoMap, reportContext));

  // Compute stats
  const stats: GenerationStats = {
    totalFiles: files.length,
    controllers: files.filter(f => f.category === "controller").length,
    services: files.filter(f => f.category === "service").length,
    dtos: files.filter(f => f.category === "dto").length,
    tests: files.filter(f => f.category === "test").length,
    enums: files.filter(f => f.category === "enum").length,
    exceptions: files.filter(f => f.category === "exception").length,
    validators: files.filter(f => f.category === "validator").length,
    configFiles: files.filter(f => f.category === "config").length,
    cloudFiles: files.filter(f => f.category === "cloud").length,
    totalLinesGenerated: files.reduce((sum, f) => sum + f.content.split("\n").length, 0),
  };

  // Step 4.2 — Syntax verification
  const compilationResult = verifySyntax(files);

  return { files, stats, warnings, compilationResult };
}

// ─── R1: Semantic Endpoint Naming ──────────────────────────────────────────

function inferSemanticEndpoint(uc: UseCaseIR, domain: string): { path: string; method: string } {
  const className = uc.className;
  const name = className.replace(/UC$/, "").replace(/UseCase$/, "");

  // Extract action verb and resource from class name
  // e.g., ActiverCarteUC → action="Activer", resource="Carte"
  const actionMatch = name.match(/^([A-Z][a-z]+)(.+)$/);
  const action = actionMatch ? actionMatch[1].toLowerCase() : name.toLowerCase();
  const resource = actionMatch ? actionMatch[2] : domain;

  // Pluralize resource for REST convention
  const resourcePlural = pluralize(resource.toLowerCase());

  // Detect if there's an ID parameter in the VoIn
  const hasIdParam = detectIdParam(uc);

  // Map action verbs to HTTP methods and path patterns
  const verbMap: Record<string, { method: string; pathSuffix: string }> = {
    // GET verbs
    "get": { method: "GET", pathSuffix: "" },
    "find": { method: "GET", pathSuffix: "" },
    "search": { method: "GET", pathSuffix: "/search" },
    "list": { method: "GET", pathSuffix: "" },
    "consulter": { method: "GET", pathSuffix: "" },
    "charger": { method: "GET", pathSuffix: "" },
    "lister": { method: "GET", pathSuffix: "" },
    "rechercher": { method: "GET", pathSuffix: "/search" },
    "recuperer": { method: "GET", pathSuffix: "" },
    // POST verbs (creation/action)
    "create": { method: "POST", pathSuffix: "" },
    "creer": { method: "POST", pathSuffix: "" },
    "ajouter": { method: "POST", pathSuffix: "" },
    "activer": { method: "POST", pathSuffix: "/activer" },
    "bloquer": { method: "POST", pathSuffix: "/bloquer" },
    "debloquer": { method: "POST", pathSuffix: "/debloquer" },
    "valider": { method: "POST", pathSuffix: "/valider" },
    "traiter": { method: "POST", pathSuffix: "/traiter" },
    "executer": { method: "POST", pathSuffix: "/executer" },
    "simuler": { method: "POST", pathSuffix: "/simulation" },
    "envoyer": { method: "POST", pathSuffix: "/envoi" },
    "receptionner": { method: "POST", pathSuffix: "/reception" },
    "process": { method: "POST", pathSuffix: "" },
    "submit": { method: "POST", pathSuffix: "" },
    "execute": { method: "POST", pathSuffix: "" },
    // PUT verbs
    "update": { method: "PUT", pathSuffix: "" },
    "modifier": { method: "PUT", pathSuffix: "" },
    "mettre": { method: "PUT", pathSuffix: "" },
    // DELETE verbs
    "delete": { method: "DELETE", pathSuffix: "" },
    "supprimer": { method: "DELETE", pathSuffix: "" },
    "annuler": { method: "DELETE", pathSuffix: "" },
  };

  const mapping = verbMap[action] || { method: uc.httpMethod || "POST", pathSuffix: "" };

  // Build the path
  let path: string;
  if (hasIdParam) {
    const idParam = getIdParamName(uc);
    path = `/api/v1/${resourcePlural}/{${idParam}}${mapping.pathSuffix}`;
  } else if (mapping.method === "GET" && !mapping.pathSuffix) {
    // List endpoint
    path = `/api/v1/${resourcePlural}`;
  } else {
    path = `/api/v1/${resourcePlural}${mapping.pathSuffix}`;
  }

  return { path, method: mapping.method, subPath: mapping.pathSuffix || "" };
}

function detectIdParam(uc: UseCaseIR): boolean {
  // Check if any VoIn field looks like an identifier
  const idPatterns = /^(id|num|code|ref|numero|identifiant|numCarte|cardNumber|numCompte|accountNumber|clientId|customerId)/i;
  // Check from className
  const name = uc.className.replace(/UC$/, "").replace(/UseCase$/, "");
  // If the action implies a specific resource (Activer, Bloquer, Consulter), it likely needs an ID
  const actionNeedsId = /^(activer|bloquer|debloquer|consulter|charger|modifier|supprimer|get|find|update|delete)/i;
  const actionMatch = name.match(/^([A-Z][a-z]+)/);
  if (actionMatch && actionNeedsId.test(actionMatch[1])) return true;
  return false;
}

function getIdParamName(uc: UseCaseIR): string {
  // Try to infer the ID parameter name from the resource
  const name = uc.className.replace(/UC$/, "").replace(/UseCase$/, "");
  const resourceMatch = name.match(/^[A-Z][a-z]+(.+)$/);
  const resource = resourceMatch ? resourceMatch[1] : "resource";
  // Common patterns
  if (/carte/i.test(resource)) return "numCarte";
  if (/compte/i.test(resource)) return "numCompte";
  if (/client/i.test(resource)) return "clientId";
  if (/credit/i.test(resource)) return "creditId";
  if (/demande/i.test(resource)) return "demandeId";
  if (/virement/i.test(resource)) return "virementId";
  if (/paiement/i.test(resource)) return "paiementId";
  return resource.charAt(0).toLowerCase() + resource.slice(1) + "Id";
}

function pluralize(word: string): string {
  if (word.endsWith("s") || word.endsWith("x") || word.endsWith("z")) return word;
  if (word.endsWith("eau")) return word + "x";
  return word + "s";
}

// ─── R10: Bean Validation Inference ────────────────────────────────────────

function inferBeanValidation(field: DtoFieldIR, imports: Set<string>): string[] {
  const annotations: string[] = [];
  const name = field.name.toLowerCase();
  const type = field.type;

  // Preserve source annotations
  if (field.required) {
    if (type === "String") {
      imports.add("import jakarta.validation.constraints.NotBlank;");
      annotations.push("    @NotBlank");
    } else {
      imports.add("import jakarta.validation.constraints.NotNull;");
      annotations.push("    @NotNull");
    }
  }

  // R10: Infer validation from field name patterns
  // Card number pattern
  if (name.includes("numcarte") || name.includes("cardnumber") || name.includes("numerocarte")) {
    imports.add("import jakarta.validation.constraints.Pattern;");
    annotations.push(`    @Pattern(regexp = "^[0-9]{16}$", message = "Card number must be 16 digits")`);
  }
  // Amount pattern
  else if ((type === "BigDecimal" || type === "Double" || type === "double") &&
    (name.includes("montant") || name.includes("amount") || name.includes("solde") || name.includes("balance"))) {
    imports.add("import jakarta.validation.constraints.DecimalMin;");
    imports.add("import jakarta.validation.constraints.Digits;");
    annotations.push(`    @DecimalMin(value = "0.00", message = "Amount must be positive")`);
    annotations.push(`    @Digits(integer = 15, fraction = 2, message = "Amount format: max 15 integer digits, 2 decimal")`);
  }
  // Email pattern
  else if (name.includes("email") || name.includes("mail")) {
    imports.add("import jakarta.validation.constraints.Email;");
    annotations.push(`    @Email(message = "Invalid email format")`);
  }
  // Phone pattern
  else if (name.includes("telephone") || name.includes("phone") || name.includes("tel") || name.includes("gsm")) {
    imports.add("import jakarta.validation.constraints.Pattern;");
    annotations.push(`    @Pattern(regexp = "^\\\\+?[0-9]{8,15}$", message = "Invalid phone number")`);
  }
  // RIB/IBAN from source annotations
  for (const va of field.validationAnnotations) {
    if (va.startsWith("ValidRIB") || va.startsWith("ValidIBAN")) {
      annotations.push(`    @${va}`);
    } else if (va.startsWith("NotNull") && !field.required) {
      imports.add("import jakarta.validation.constraints.NotNull;");
      annotations.push("    @NotNull");
    } else if (va.startsWith("Size")) {
      imports.add("import jakarta.validation.constraints.Size;");
      annotations.push(`    @${va}`);
    } else if (va.startsWith("Pattern")) {
      imports.add("import jakarta.validation.constraints.Pattern;");
      annotations.push(`    @${va}`);
    }
  }

  return annotations;
}

// ─── Main Application ───────────────────────────────────────────────────────

function generateMainApplication(basePackage: string, basePath: string, ir: ProjectIR): GeneratedFile {
  const appName = toPascalCase(ir.artifactId) + "Application";
  return {
    path: `${basePath}/${appName}.java`,
    category: "main",
    content: `package ${basePackage};

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * ${ir.projectName || ir.artifactId} — Spring Boot 3.2 Application.
 * Auto-generated from EJB legacy project by Compleo Modernizer.
 */
@SpringBootApplication
public class ${appName} {

    public static void main(String[] args) {
        SpringApplication.run(${appName}.class, args);
    }
}
`,
  };
}

// ─── DTO Generator — R9, R10 ───────────────────────────────────────────────

function generateDto(basePackage: string, basePath: string, dto: DtoIR, enums: EnumIR[]): GeneratedFile {
  const enumNames = new Set(enums.map(e => e.className));
  const imports = new Set<string>();
  imports.add("import lombok.Data;");
  imports.add("import lombok.NoArgsConstructor;");
  imports.add("import lombok.AllArgsConstructor;");
  imports.add("import lombok.Builder;");

  const isRequest = dto.direction === "in";
  const newClassName = dto.className
    .replace(/VoIn$/, "RequestDTO")
    .replace(/VoOut$/, "ResponseDTO")
    .replace(/Dto$/, "DTO");

  const fieldLines: string[] = [];
  for (const field of dto.fields) {
    // R10: Infer Bean Validation
    const annotations = isRequest ? inferBeanValidation(field, imports) : [];

    // CORRECTION v5.2: Semantic type inference — String fields named date* → LocalDate
    let inferredType = field.type;
    if (field.type === "String" && /^date/i.test(field.name)) {
      inferredType = "LocalDate";
    }
    const javaType = mapToSpringType(inferredType, field.isEnum, enumNames, imports);
    for (const a of annotations) fieldLines.push(a);
    fieldLines.push(`    private ${javaType} ${field.name};`);
    fieldLines.push("");
  }

  return {
    path: `${basePath}/dto/${newClassName}.java`,
    category: "dto",
    content: `package ${basePackage}.dto;

${[...imports].sort().join("\n")}

/**
 * ${isRequest ? "Request" : "Response"} DTO for ${dto.className}.
 * Auto-generated from legacy ${dto.className}.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ${newClassName} {

${fieldLines.join("\n")}
}
`,
  };
}

function mapToSpringType(rawType: string, isEnum: boolean, enumNames: Set<string>, imports: Set<string>): string {
  if (isEnum || enumNames.has(rawType)) return rawType;

  const typeMap: Record<string, { type: string; import?: string }> = {
    "String": { type: "String" },
    "int": { type: "int" },
    "Integer": { type: "Integer" },
    "long": { type: "long" },
    "Long": { type: "Long" },
    "double": { type: "double" },
    "Double": { type: "Double" },
    "float": { type: "float" },
    "Float": { type: "Float" },
    "boolean": { type: "boolean" },
    "Boolean": { type: "Boolean" },
    "BigDecimal": { type: "BigDecimal", import: "import java.math.BigDecimal;" },
    "BigInteger": { type: "BigInteger", import: "import java.math.BigInteger;" },
    "LocalDate": { type: "LocalDate", import: "import java.time.LocalDate;" },
    "LocalDateTime": { type: "LocalDateTime", import: "import java.time.LocalDateTime;" },
    "Date": { type: "LocalDateTime", import: "import java.time.LocalDateTime;" },
    "byte[]": { type: "byte[]" },
  };

  // Handle generics: List<X>, Set<X>, Map<K,V>
  const genericMatch = rawType.match(/^(\w+)<(.+)>$/);
  if (genericMatch) {
    const container = genericMatch[1];
    const innerRaw = genericMatch[2];

    if (container === "List" || container === "ArrayList" || container === "LinkedList") {
      imports.add("import java.util.List;");
      const innerResolved = mapToSpringType(innerRaw.trim(), false, enumNames, imports);
      return `List<${innerResolved}>`;
    }
    if (container === "Set" || container === "HashSet" || container === "TreeSet") {
      imports.add("import java.util.Set;");
      const innerResolved = mapToSpringType(innerRaw.trim(), false, enumNames, imports);
      return `Set<${innerResolved}>`;
    }
    if (container === "Map" || container === "HashMap" || container === "TreeMap") {
      imports.add("import java.util.Map;");
      const parts = innerRaw.split(",").map(p => p.trim());
      if (parts.length === 2) {
        const k = mapToSpringType(parts[0], false, enumNames, imports);
        const v = mapToSpringType(parts[1], false, enumNames, imports);
        return `Map<${k}, ${v}>`;
      }
    }
    return rawType;
  }

  // Handle raw collection types without generics
  if (rawType === "List" || rawType === "ArrayList") {
    imports.add("import java.util.List;");
    return "List<String>";
  }
  if (rawType === "Set" || rawType === "HashSet") {
    imports.add("import java.util.Set;");
    return "Set<String>";
  }
  if (rawType === "Map" || rawType === "HashMap") {
    imports.add("import java.util.Map;");
    return "Map<String, String>";
  }

  // Handle arrays
  const baseType = rawType.replace(/\[\]$/, "").trim();
  const mapping = typeMap[baseType];
  if (mapping) {
    if (mapping.import) imports.add(mapping.import);
    if (rawType.endsWith("[]")) return mapping.type + "[]";
    return mapping.type;
  }

  // R9: Never emit "Object" — preserve original type name
  return rawType;
}

// ─── Enum Generator ─────────────────────────────────────────────────────────

function generateEnum(basePackage: string, basePath: string, en: EnumIR): GeneratedFile {
  const values = en.values.map(v => `    ${v}`).join(",\n");
  return {
    path: `${basePath}/enums/${en.className}.java`,
    category: "enum",
    content: `package ${basePackage}.enums;

/**
 * Enum ${en.className}.
 * Preserved from legacy project.
 */
public enum ${en.className} {
${values}
}
`,
  };
}

// ─── Exception Generator ────────────────────────────────────────────────────

function generateException(basePackage: string, basePath: string, ex: ExceptionIR): GeneratedFile {
  return {
    path: `${basePath}/exception/${ex.className}.java`,
    category: "exception",
    content: `package ${basePackage}.exception;

/**
 * ${ex.className} — Business exception.
 * Migrated from legacy ${ex.extendsClass}.
 */
public class ${ex.className} extends RuntimeException {

    public ${ex.className}() {
        super();
    }

    public ${ex.className}(String message) {
        super(message);
    }

    public ${ex.className}(String message, Throwable cause) {
        super(message, cause);
    }
}
`,
  };
}

// R3: Semantic HTTP status codes in GlobalExceptionHandler
function generateGlobalExceptionHandler(basePackage: string, basePath: string, exceptions: ExceptionIR[]): GeneratedFile {
  const handlers = exceptions.map(ex => {
    // Map exception type to appropriate HTTP status
    const exName = ex.className.toLowerCase();
    let status = "HttpStatus.BAD_REQUEST";
    let statusCode = "400";
    if (exName.includes("notfound") || exName.includes("introuvable") || exName.includes("inexistant")) {
      status = "HttpStatus.NOT_FOUND";
      statusCode = "404";
    } else if (exName.includes("unauthorized") || exName.includes("nonautorise")) {
      status = "HttpStatus.UNAUTHORIZED";
      statusCode = "401";
    } else if (exName.includes("forbidden") || exName.includes("interdit")) {
      status = "HttpStatus.FORBIDDEN";
      statusCode = "403";
    } else if (exName.includes("validation") || exName.includes("regle") || exName.includes("metier")) {
      status = "HttpStatus.UNPROCESSABLE_ENTITY";
      statusCode = "422";
    }
    return `
    @ExceptionHandler(${ex.className}.class)
    public ResponseEntity<ErrorResponse> handle${ex.className}(${ex.className} ex) {
        log.warn("Business exception [${statusCode}]: {}", ex.getMessage());
        return ResponseEntity.status(${status})
            .body(new ErrorResponse("${ex.className.replace(/Exception$/, "").toUpperCase()}", ex.getMessage()));
    }`;
  }).join("\n");

  return {
    path: `${basePath}/exception/GlobalExceptionHandler.java`,
    category: "exception",
    content: `package ${basePackage}.exception;

import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.MethodArgumentNotValidException;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.RestControllerAdvice;

/**
 * Global exception handler — centralizes error responses.
 * R4: Controllers never catch exceptions; this handler does.
 * Auto-generated by Compleo Modernizer.
 */
@Slf4j
@RestControllerAdvice
public class GlobalExceptionHandler {

    public record ErrorResponse(String code, String message) {}
${handlers}

    @ExceptionHandler(MethodArgumentNotValidException.class)
    public ResponseEntity<ErrorResponse> handleValidation(MethodArgumentNotValidException ex) {
        String message = ex.getBindingResult().getFieldErrors().stream()
            .map(e -> e.getField() + ": " + e.getDefaultMessage())
            .reduce((a, b) -> a + "; " + b)
            .orElse("Validation failed");
        log.warn("Validation error: {}", message);
        return ResponseEntity.badRequest()
            .body(new ErrorResponse("VALIDATION_ERROR", message));
    }

    @ExceptionHandler(BusinessRuleException.class)
    public ResponseEntity<ErrorResponse> handleBusinessRule(BusinessRuleException ex) {
        log.warn("Business rule violation [422]: {}", ex.getMessage());
        return ResponseEntity.status(HttpStatus.UNPROCESSABLE_ENTITY)
            .body(new ErrorResponse("BUSINESS_RULE_VIOLATION", ex.getMessage()));
    }

    @ExceptionHandler(Exception.class)
    public ResponseEntity<ErrorResponse> handleGeneral(Exception ex) {
        log.error("Unexpected error", ex);
        return ResponseEntity.internalServerError()
            .body(new ErrorResponse("INTERNAL_ERROR", "An unexpected error occurred"));
    }
}
`,
  };
}

// ─── Validator Generator ────────────────────────────────────────────────────

function generateValidator(basePackage: string, basePath: string, val: ValidatorIR): GeneratedFile {
  if (val.className.endsWith("Validator")) {
    return {
      path: `${basePath}/validation/${val.className}.java`,
      category: "validator",
      content: `package ${basePackage}.validation;

import jakarta.validation.ConstraintValidator;
import jakarta.validation.ConstraintValidatorContext;

/**
 * ${val.className} — Custom validator for @${val.annotationName}.
 * Migrated from legacy project.
 */
public class ${val.className} implements ConstraintValidator<${val.annotationName}, String> {

    @Override
    public void initialize(${val.annotationName} constraintAnnotation) {
        // No-op
    }

    @Override
    public boolean isValid(String value, ConstraintValidatorContext context) {
        if (value == null || value.isBlank()) return true;
        // TODO: Implement validation logic from legacy code
        return value.length() >= 10;
    }
}
`,
    };
  }

  return {
    path: `${basePath}/validation/${val.className}.java`,
    category: "validator",
    content: `package ${basePackage}.validation;

import jakarta.validation.Constraint;
import jakarta.validation.Payload;
import java.lang.annotation.*;

/**
 * @${val.className} — Custom validation annotation.
 * Migrated from legacy project.
 */
@Documented
@Constraint(validatedBy = ${val.className.replace("Valid", "")}Validator.class)
@Target({ElementType.FIELD, ElementType.PARAMETER})
@Retention(RetentionPolicy.RUNTIME)
public @interface ${val.className} {
    String message() default "Invalid value";
    Class<?>[] groups() default {};
    Class<? extends Payload>[] payload() default {};
}
`,
  };
}

// ─── Domain Service Generator — R6, R7, R8 ─────────────────────────────────

function generateDomainService(
  basePackage: string, basePath: string, domain: string,
  useCases: UseCaseIR[], dtoMap: Map<string, DtoIR>, ir: ProjectIR
): GeneratedFile {
  const serviceName = toPascalCase(domain) + "Service";
  const imports = new Set<string>();
  // R6: Constructor injection via Lombok
  imports.add("import lombok.RequiredArgsConstructor;");
  imports.add("import lombok.extern.slf4j.Slf4j;");
  imports.add("import org.springframework.stereotype.Service;");
  imports.add("import org.springframework.transaction.annotation.Transactional;");

  const methods: string[] = [];

  for (const uc of useCases) {
    const methodName = toMethodName(uc.className);
    const reqDto = dtoMap.get(uc.voInType);
    const resDto = dtoMap.get(uc.voOutType);

    const reqType = reqDto ? mapDtoClassName(reqDto.className) : "Void";
    const resType = resDto ? mapDtoClassName(resDto.className) : "Void";

    if (reqDto) imports.add(`import ${basePackage}.dto.${reqType};`);
    if (resDto) imports.add(`import ${basePackage}.dto.${resType};`);

    // R7: @Transactional at the right level
    let txAnnotation = "";
    if (uc.transactional) {
      if (uc.transactional.readOnly) {
        txAnnotation = "    @Transactional(readOnly = true)\n";
      } else if (uc.transactional.rollbackFor) {
        txAnnotation = `    @Transactional(rollbackFor = ${uc.transactional.rollbackFor}.class)\n`;
      } else {
        txAnnotation = "    @Transactional\n";
      }
    } else {
      // Infer from method semantics
      const semantic = inferSemanticEndpoint(uc, domain);
      if (semantic.method === "GET") {
        txAnnotation = "    @Transactional(readOnly = true)\n";
      } else {
        txAnnotation = "    @Transactional\n";
      }
    }

    const paramType = reqType !== "Void" ? `${reqType} request` : "";
    const returnType = resType !== "Void" ? resType : "void";

    // R5: Javadoc from source
    const javadoc = (uc as any).useCaseDescription || (uc as any).javadoc || "";
    const javadocLine = javadoc ? `\n     * ${javadoc}` : "";

    methods.push(`
${txAnnotation}    /**
     * ${uc.className} — ${uc.bianDomain || domain} / ${uc.bianAction || methodName}.${javadocLine}
     * Migrated from legacy UseCase: ${uc.className}
     */
    public ${returnType} ${methodName}(${paramType}) {
        log.info("=== Starting ${methodName} ===");
${generateServiceMethodBody(uc, reqDto, resDto, reqType, resType)}
        log.info("=== Ending ${methodName} ===");
${returnType !== "void" ? "        return response;" : ""}
    }`);
  }

  // R6: Collect all injected services for constructor injection
  const allInjected = new Set<string>();
  for (const uc of useCases) {
    for (const svc of uc.injectedServices) {
      allInjected.add(svc.type);
    }
  }

  // R8: Generate field declarations for injected dependencies
  const injectedFields = [...allInjected].map(s => {
    const fieldName = s.charAt(0).toLowerCase() + s.slice(1);
    return `    private final ${s} ${fieldName};`;
  });

  return {
    path: `${basePath}/service/${serviceName}.java`,
    category: "service",
    content: `package ${basePackage}.service;

${[...imports].sort().join("\n")}

/**
 * ${serviceName} — Domain service for ${domain}.
 * Contains ${useCases.length} migrated use case(s).
 * Auto-generated from EJB legacy project by Compleo Modernizer.
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class ${serviceName} {

${injectedFields.length > 0 ? injectedFields.join("\n") + "\n" : "    // No external dependencies detected\n"}
${methods.join("\n")}
}
`,
  };
}

function generateServiceMethodBody(
  uc: UseCaseIR, reqDto: DtoIR | undefined, resDto: DtoIR | undefined,
  reqType: string, resType: string
): string {
  const lines: string[] = [];

  if (resDto && resType !== "Void") {
    // R11: Use builder pattern for realistic data
    lines.push(`        ${resType} response = ${resType}.builder()`);

    // Map fields from request to response where names match
    if (reqDto) {
      for (const outField of resDto.fields) {
        const inField = reqDto.fields.find(f => f.name === outField.name);
        if (inField) {
          lines.push(`            .${outField.name}(request.get${capitalize(outField.name)}())`);
        }
      }
    }

    // Set standard response fields
    for (const field of resDto.fields) {
      if (field.name === "codeRetour") {
        lines.push(`            .codeRetour("000")`);
      } else if (field.name === "messageRetour") {
        lines.push(`            .messageRetour("Operation completed successfully")`);
      }
    }

    lines.push(`            .build();`);
  }

  // R8: Add TODO with Magix transaction code if present
  const magixService = uc.injectedServices.find(s =>
    s.type.toLowerCase().includes("magix") || s.type.toLowerCase().includes("service")
  );
  if (magixService) {
    lines.push(`        // TODO: Implement call to ${magixService.type} — migrated from @EJB ${magixService.fieldName}`);
    lines.push(`        // Original transaction code: see legacy ${uc.className}`);
  } else {
    lines.push(`        // TODO: Implement business logic from legacy ${uc.className}`);
  }

  return lines.join("\n");
}

// ─── Domain Controller Generator — R1, R2, R3, R4, R5 ─────────────────────

function generateDomainController(
  basePackage: string, basePath: string, domain: string,
  useCases: UseCaseIR[], dtoMap: Map<string, DtoIR>
): GeneratedFile {
  const controllerName = toPascalCase(domain) + "Controller";
  const serviceName = toPascalCase(domain) + "Service";
  const serviceVar = domain + "Service";
  const imports = new Set<string>();
  // R6: Constructor injection
  imports.add("import lombok.RequiredArgsConstructor;");
  imports.add("import lombok.extern.slf4j.Slf4j;");
  imports.add("import org.springframework.http.ResponseEntity;");
  imports.add("import org.springframework.web.bind.annotation.*;");
  imports.add(`import ${basePackage}.service.${serviceName};`);
  imports.add("import io.swagger.v3.oas.annotations.Operation;");
  imports.add("import io.swagger.v3.oas.annotations.tags.Tag;");

  const endpoints: string[] = [];

  for (const uc of useCases) {
    const methodName = toMethodName(uc.className);
    const reqDto = dtoMap.get(uc.voInType);
    const resDto = dtoMap.get(uc.voOutType);

    const reqType = reqDto ? mapDtoClassName(reqDto.className) : null;
    const resType = resDto ? mapDtoClassName(resDto.className) : "Void";

    if (reqType) imports.add(`import ${basePackage}.dto.${reqType};`);
    if (resType !== "Void") imports.add(`import ${basePackage}.dto.${resType};`);
    if (reqType) imports.add("import jakarta.validation.Valid;");

    // R1: Semantic endpoint naming
    const semantic = inferSemanticEndpoint(uc, domain);
    const httpMethod = semantic.method;
    // CORRECTION v5.2: Compute endpoint path relative to the controller's @RequestMapping base path
    // The base path is /api/v1/{domain_plural}, so we strip it from the semantic path.
    // If the semantic path uses a different resource (e.g. /api/v1/internes for VirementInterneUC),
    // we use only the pathSuffix from the verb mapping, not the full semantic path.
    const controllerBasePath = `/api/v1/${pluralize(domain.toLowerCase())}`;
    let endpointPath = semantic.path.startsWith(controllerBasePath)
      ? semantic.path.substring(controllerBasePath.length)
      : semantic.subPath || "";

    // R2: PathVariable detection
    const hasIdParam = detectIdParam(uc);
    const idParamName = hasIdParam ? getIdParamName(uc) : "";

    // Build parameter list — R2
    let paramList = "";
    if (hasIdParam && reqType) {
      paramList = `@PathVariable String ${idParamName}, @Valid @RequestBody ${reqType} request`;
    } else if (hasIdParam) {
      paramList = `@PathVariable String ${idParamName}`;
    } else if (reqType) {
      paramList = `@Valid @RequestBody ${reqType} request`;
    }

    // R3: Semantic HTTP status
    const isCreation = httpMethod === "POST" && /^(creer|create|ajouter|add)/i.test(uc.className.replace(/UC$/, ""));
    let responseStatement: string;
    if (isCreation) {
      imports.add("import org.springframework.http.HttpStatus;");
      imports.add("import java.net.URI;");
      responseStatement = resType !== "Void"
        ? `        ${resType} result = ${serviceVar}.${methodName}(${reqType ? "request" : ""});\n        return ResponseEntity.status(HttpStatus.CREATED).body(result);`
        : `        ${serviceVar}.${methodName}(${reqType ? "request" : ""});\n        return ResponseEntity.status(HttpStatus.CREATED).build();`;
    } else {
      responseStatement = resType !== "Void"
        ? `        ${resType} result = ${serviceVar}.${methodName}(${reqType ? "request" : ""});\n        return ResponseEntity.ok(result);`
        : `        ${serviceVar}.${methodName}(${reqType ? "request" : ""});\n        return ResponseEntity.ok().build();`;
    }

    // R5: Javadoc → @Operation OpenAPI
    const javadoc = (uc as any).useCaseDescription || (uc as any).javadoc || "";
    const operationSummary = javadoc || `${methodName} — ${domain}`;

    const httpAnnotation = getHttpAnnotation(httpMethod, endpointPath || "/" + methodName.replace(/([a-z])([A-Z])/g, "$1-$2").toLowerCase());
    const returnGeneric = resType !== "Void" ? resType : "Void";

    // R4: No try/catch — exceptions handled by GlobalExceptionHandler
    endpoints.push(`
    /**
     * ${httpMethod} ${semantic.path}
     * ${uc.bianDomain ? `BIAN: ${uc.bianDomain} / ${uc.bianAction}` : `UseCase: ${uc.className}`}
     * ${javadoc ? javadoc : ""}
     */
    @Operation(summary = "${operationSummary}")
    ${httpAnnotation}
    public ResponseEntity<${returnGeneric}> ${methodName}(${paramList}) {
        log.info("${httpMethod} ${semantic.path}");
${responseStatement}
    }`);
  }

  // R1: Base path uses pluralized domain
  const basePath2 = `/api/v1/${pluralize(domain.toLowerCase())}`;

  return {
    path: `${basePath}/controller/${controllerName}.java`,
    category: "controller",
    content: `package ${basePackage}.controller;

${[...imports].sort().join("\n")}

/**
 * ${controllerName} — REST API for ${domain} domain.
 * ${useCases.length} endpoint(s) migrated from EJB UseCases.
 * Auto-generated by Compleo Modernizer.
 */
@Slf4j
@RestController
@RequestMapping("${basePath2}")
@RequiredArgsConstructor
@Tag(name = "${toPascalCase(domain)}", description = "API for ${domain} operations")
public class ${controllerName} {

    private final ${serviceName} ${serviceVar};
${endpoints.join("\n")}
}
`,
  };
}

function getHttpAnnotation(method: string, path: string): string {
  // Clean up path
  const cleanPath = path.startsWith("/") ? path : "/" + path;
  switch (method) {
    case "GET": return `@GetMapping("${cleanPath}")`;
    case "POST": return `@PostMapping("${cleanPath}")`;
    case "PUT": return `@PutMapping("${cleanPath}")`;
    case "DELETE": return `@DeleteMapping("${cleanPath}")`;
    case "PATCH": return `@PatchMapping("${cleanPath}")`;
    default: return `@PostMapping("${cleanPath}")`;
  }
}

// ─── Test Generator — R11, R12 ─────────────────────────────────────────────

function generateDomainControllerTest(
  basePackage: string, testPath: string, domain: string,
  useCases: UseCaseIR[], dtoMap: Map<string, DtoIR>
): GeneratedFile {
  const controllerName = toPascalCase(domain) + "Controller";
  const serviceName = toPascalCase(domain) + "Service";

  const testImports = new Set<string>();
  testImports.add("import org.junit.jupiter.api.DisplayName;");
  testImports.add("import org.junit.jupiter.api.Test;");
  testImports.add("import org.springframework.beans.factory.annotation.Autowired;");
  testImports.add("import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;");
  testImports.add("import org.springframework.boot.test.mock.bean.MockBean;");
  testImports.add("import org.springframework.http.MediaType;");
  testImports.add("import org.springframework.test.web.servlet.MockMvc;");
  testImports.add(`import ${basePackage}.service.${serviceName};`);
  testImports.add("import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;");
  testImports.add("import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;");
  testImports.add("import static org.mockito.ArgumentMatchers.*;");
  testImports.add("import static org.mockito.Mockito.when;");
  // CORRECTION v5.2: Import BusinessRuleException for 422 tests
  testImports.add(`import ${basePackage}.exception.BusinessRuleException;`);

  const testMethods: string[] = [];

  for (const uc of useCases) {
    const methodName = toMethodName(uc.className);
    const reqDto = dtoMap.get(uc.voInType);
    const resDto = dtoMap.get(uc.voOutType);
    const reqType = reqDto ? mapDtoClassName(reqDto.className) : null;
    const resType = resDto ? mapDtoClassName(resDto.className) : null;

    if (reqType) testImports.add(`import ${basePackage}.dto.${reqType};`);
    if (resType) testImports.add(`import ${basePackage}.dto.${resType};`);

    const semantic = inferSemanticEndpoint(uc, domain);
    const httpMethod = semantic.method.toLowerCase();
    // CORRECTION v5.2: Use the full semantic path for test URLs (tests call the full URL, not relative)
    const url = semantic.path
      .replace("{numCarte}", "1234567890123456")
      .replace("{numCompte}", "001234567890")
      .replace(/{(\w+)Id}/g, "12345")
      .replace(/{(\w+)}/g, "test-value");

    // CORRECTION v5.2: Detect creation endpoints for correct HTTP status assertion
    const isCreation = semantic.method === "POST" && /^(creer|create|ajouter|add)/i.test(uc.className.replace(/UC$/, "").replace(/UseCase$/, ""));

    // R11: Build realistic request body
    const requestBody = reqDto ? buildRealisticRequestJson(reqDto) : null;

    // R11: Build realistic response
    const responseSetup = resDto ? buildRealisticResponseMock(resDto, resType!, methodName, domain + "Service") : null;

    // ─── Test 1: Happy path (R12) ───
    // CORRECTION v5.2: Use isCreated() for creation endpoints, isOk() for others
    const expectedStatus = isCreation ? "isCreated" : "isOk";
    testMethods.push(`
    @Test
    @DisplayName("${semantic.method} ${semantic.path} — happy path")
    void ${methodName}_shouldReturnOk() throws Exception {
${responseSetup ? responseSetup : ""}
        // when & then
        mockMvc.perform(${httpMethod}("${url}")${requestBody ? `
                .contentType(MediaType.APPLICATION_JSON)
                .content(${JSON.stringify(requestBody)})` : ""})
                .andExpect(status().${expectedStatus}())${resDto ? buildJsonPathAssertions(resDto) : ""};
    }`);

    // ─── Test 2: Validation error (R12) — for POST/PUT with body ───
    if (reqType && (semantic.method === "POST" || semantic.method === "PUT")) {
      testMethods.push(`
    @Test
    @DisplayName("${semantic.method} ${semantic.path} — validation error with empty body")
    void ${methodName}_shouldReturnBadRequest_whenInvalidInput() throws Exception {
        // when & then
        mockMvc.perform(${httpMethod}("${url}")
                .contentType(MediaType.APPLICATION_JSON)
                .content("{}"))
                .andExpect(status().isBadRequest());
    }`);
    }

    // ─── Test 3: Business rule violation (R12) ───
    // CORRECTION v5.2: Use BusinessRuleException (handled by GlobalExceptionHandler → 422)
    testMethods.push(`
    @Test
    @DisplayName("${semantic.method} ${semantic.path} — business rule violation")
    void ${methodName}_shouldReturn422_whenBusinessRuleViolated() throws Exception {
        // given — service throws a business rule exception
        when(${domain}Service.${methodName}(${reqType ? "any()" : ""}))
            .thenThrow(new BusinessRuleException("Règle métier violée"));

        // when & then
        mockMvc.perform(${httpMethod}("${url}")${requestBody ? `
                .contentType(MediaType.APPLICATION_JSON)
                .content(${JSON.stringify(requestBody)})` : ""})
                .andExpect(status().isUnprocessableEntity());
    }`);
  }

  return {
    path: `${testPath}/controller/${controllerName}Test.java`,
    category: "test",
    content: `package ${basePackage}.controller;

${[...testImports].sort().join("\n")}

/**
 * Tests for ${controllerName}.
 * R12: Minimum 3 tests per endpoint (happy path, validation, business rule).
 * Auto-generated by Compleo Modernizer.
 */
@WebMvcTest(${controllerName}.class)
class ${controllerName}Test {

    @Autowired
    private MockMvc mockMvc;

    @MockBean
    private ${serviceName} ${domain}Service;
${testMethods.join("\n")}
}
`,
  };
}

// R11: Build realistic JSON request body from DTO fields
function buildRealisticRequestJson(dto: DtoIR): string {
  const obj: Record<string, any> = {};
  for (const field of dto.fields) {
    obj[field.name] = getRealisticValue(field);
  }
  return JSON.stringify(obj);
}

function getRealisticValue(field: DtoFieldIR): any {
  const name = field.name.toLowerCase();
  const type = field.type;

  // Name-based realistic values
  if (name.includes("numcarte") || name.includes("cardnumber")) return "1234567890123456";
  if (name.includes("numcompte") || name.includes("accountnumber")) return "001234567890";
  if (name.includes("montant") || name.includes("amount")) return 1500.00;
  if (name.includes("solde") || name.includes("balance")) return 25000.50;
  if (name.includes("email")) return "client@example.com";
  if (name.includes("telephone") || name.includes("phone")) return "+212600000000";
  if (name.includes("nom") || name.includes("name") || name.includes("prenom")) return "Mohammed";
  if (name.includes("adresse") || name.includes("address")) return "123 Bd Mohammed V, Casablanca";
  if (name.includes("code") && name.includes("pays")) return "MA";
  if (name.includes("code") && name.includes("retour")) return "000";
  if (name.includes("code") && name.includes("activation")) return "12345";
  if (name.includes("code")) return "CODE001";
  if (name.includes("date")) return "2024-01-15";
  if (name.includes("statut") || name.includes("status")) return "ACTIVE";
  if (name.includes("message")) return "Operation completed successfully";
  if (name.includes("description")) return "Test description";
  if (name.includes("reference") || name.includes("ref")) return "REF-2024-001";

  // Type-based fallback
  if (type === "String") return "test-value";
  if (type === "int" || type === "Integer" || type === "long" || type === "Long") return 1;
  if (type === "double" || type === "Double" || type === "float" || type === "Float") return 1.0;
  if (type === "BigDecimal") return 100.00;
  if (type === "boolean" || type === "Boolean") return true;
  if (type === "LocalDate" || type === "Date") return "2024-01-15";
  return "test";
}

// R11: Build mock response setup
function buildRealisticResponseMock(dto: DtoIR, resType: string, methodName: string, serviceVar: string): string {
  const lines: string[] = [];
  lines.push(`        // given — R11: realistic test data`);
  lines.push(`        ${resType} expected = ${resType}.builder()`);
  for (const field of dto.fields) {
    const val = getRealisticValue(field);
    if (typeof val === "string") {
      lines.push(`            .${field.name}("${val}")`);
    } else {
      lines.push(`            .${field.name}(${val})`);
    }
  }
  lines.push(`            .build();`);
  lines.push(`        when(${serviceVar}.${methodName}(any())).thenReturn(expected);`);
  return lines.join("\n");
}

// R11: Build jsonPath assertions from response DTO
function buildJsonPathAssertions(dto: DtoIR): string {
  const assertions: string[] = [];
  // Pick up to 3 fields for assertions
  const fieldsToAssert = dto.fields.slice(0, 3);
  for (const field of fieldsToAssert) {
    const val = getRealisticValue(field);
    if (typeof val === "string") {
      assertions.push(`\n                .andExpect(jsonPath("$.${field.name}").value("${val}"))`);
    } else if (typeof val === "number") {
      assertions.push(`\n                .andExpect(jsonPath("$.${field.name}").value(${val}))`);
    }
  }
  return assertions.join("");
}

// ─── Remote Service Adapter — R8 ───────────────────────────────────────────

function generateRemoteServiceAdapter(basePackage: string, basePath: string, remote: RemoteInterfaceIR): GeneratedFile {
  const adapterName = remote.className.replace("Remote", "Adapter");
  const adapterImports = new Set<string>();
  const methods = remote.methods.map(m => {
    const params = m.parameters.map(p => {
      const mappedType = mapToSpringType(p.type, false, new Set(), adapterImports);
      return `${mappedType} ${p.name}`;
    }).join(", ");
    const mappedReturn = mapToSpringType(m.returnType, false, new Set(), adapterImports);
    const roles = m.rolesAllowed.length > 0
      ? `\n    @PreAuthorize("hasAnyRole(${m.rolesAllowed.map(r => `'${r}'`).join(", ")})")`
      : "";
    // R8: Stub with log + UnsupportedOperationException + TODO with transaction code
    return `${roles}
    /**
     * ${m.name} — Stub for legacy @Remote method.
     * TODO: Implement the call to core banking system.
     */
    public ${mappedReturn} ${m.name}(${params}) {
        log.warn("STUB: ${m.name} called — not yet implemented");
        // TODO: Implement ${m.name} — migrated from @Remote ${remote.className}
        // TODO: Replace with actual core banking API call
        throw new UnsupportedOperationException("${m.name} not yet implemented — see legacy ${remote.className}");
    }`;
  }).join("\n\n");

  return {
    path: `${basePath}/adapter/${adapterName}.java`,
    category: "service",
    content: `package ${basePackage}.adapter;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.stereotype.Service;

/**
 * ${adapterName} — Adapter for legacy @Remote interface ${remote.className}.
 * ${remote.methods.length} method(s) to implement.
 * R8: Stub implementation — replace with actual core banking calls.
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class ${adapterName} {

${methods}
}
`,
  };
}

// ─── CORRECTION v5.2: Injected Service Stub Generator ──────────────────────────────────────────────

function generateInjectedServiceStub(
  basePackage: string, basePath: string, serviceType: string, sourceContent: string
): GeneratedFile {
  const adapterName = serviceType.endsWith("Service")
    ? serviceType.replace(/Service$/, "Adapter")
    : serviceType + "Adapter";

  // Parse method signatures from the source interface
  const methods: string[] = [];
  if (sourceContent) {
    const methodRegex = /^\s*(?:public\s+)?([\w<>,\s]+?)\s+(\w+)\s*\(([^)]*)\)\s*(?:throws\s+[\w,\s]+)?\s*;/gm;
    let mm;
    while ((mm = methodRegex.exec(sourceContent)) !== null) {
      const returnType = mm[1].trim();
      const methodName = mm[2];
      const params = mm[3].trim();
      const springReturn = returnType === "void" ? "void" : returnType;
      const defaultReturn = springReturn === "void" ? "" : springReturn === "String" ? "return \"\";" : springReturn === "boolean" ? "return false;" : `return null;`;
      methods.push(`
    /**
     * ${methodName} — Stub for legacy ${serviceType}.${methodName}.
     * TODO: Implement the call to core banking system.
     */
    public ${springReturn} ${methodName}(${params}) {
        log.warn("STUB: ${serviceType}.${methodName} called — not yet implemented");
        // TODO: Replace with actual core banking API call
        ${springReturn === "void" ? "// No return needed" : defaultReturn}
    }`);
    }
  }

  // If no methods found, generate a placeholder
  if (methods.length === 0) {
    methods.push(`
    /**
     * Placeholder — no methods could be extracted from legacy source.
     * TODO: Add methods matching the legacy ${serviceType} interface.
     */
    public void execute(String transactionCode, Map<String, String> request) {
        log.warn("STUB: ${serviceType}.execute called — not yet implemented");
        throw new UnsupportedOperationException("${serviceType}.execute not yet implemented");
    }`);
  }

  return {
    path: `${basePath}/adapter/${adapterName}.java`,
    category: "service" as const,
    content: `package ${basePackage}.adapter;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import java.util.Map;

/**
 * ${adapterName} — Stub adapter for legacy ${serviceType}.
 * Injected via @EJB in legacy use cases, now replaced by Spring DI.
 * ${methods.length} method(s) to implement.
 * CORRECTION v5.2: Auto-generated stub for non-@Remote injected services.
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class ${adapterName} {
${methods.join("\n")}
}
`,
  };
}

// ─── Config Generators ──────────────────────────────────────────────────────────────────────

function generateApplicationYml(ir: ProjectIR): GeneratedFile {
  return {
    path: "src/main/resources/application.yml",
    category: "config",
    content: `# ${ir.projectName || ir.artifactId} — Spring Boot Configuration
# Auto-generated by Compleo Modernizer

spring:
  application:
    name: ${ir.artifactId}
  datasource:
    url: \${DATABASE_URL:jdbc:mysql://localhost:3306/${ir.artifactId.replace(/-/g, "_")}}
    username: \${DATABASE_USER:root}
    password: \${DATABASE_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

server:
  port: \${PORT:8080}
  servlet:
    context-path: /

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

logging:
  level:
    root: INFO
    ${ir.groupId || "com.example"}: DEBUG

# OpenAPI / Swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
`,
  };
}

function generateApplicationProperties(ir: ProjectIR): GeneratedFile {
  return {
    path: "src/main/resources/application.properties",
    category: "config",
    content: `# ${ir.projectName || ir.artifactId} — Spring Boot Properties
# Auto-generated by Compleo Modernizer
spring.application.name=${ir.artifactId}
`,
  };
}

function generateDockerfile(ir: ProjectIR): GeneratedFile {
  return {
    path: "Dockerfile",
    category: "cloud",
    content: `# ${ir.projectName || ir.artifactId} — Multi-stage Docker build
# Auto-generated by Compleo Modernizer

# Stage 1: Build
FROM eclipse-temurin:17-jdk-alpine AS builder
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN apk add --no-cache maven && mvn clean package -DskipTests

# Stage 2: Runtime
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=builder /app/target/*.jar app.jar

# Security: non-root user
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
USER appuser

EXPOSE 8080
HEALTHCHECK --interval=30s --timeout=3s CMD wget -qO- http://localhost:8080/actuator/health || exit 1

ENTRYPOINT ["java", "-jar", "app.jar"]
`,
  };
}

function generateDockerCompose(ir: ProjectIR): GeneratedFile {
  const serviceName = ir.artifactId;
  return {
    path: "docker-compose.yml",
    category: "cloud",
    content: `# ${ir.projectName || ir.artifactId} — Docker Compose
# Auto-generated by Compleo Modernizer
version: '3.8'

services:
  ${serviceName}:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DATABASE_URL=jdbc:mysql://mysql:3306/${serviceName.replace(/-/g, "_")}
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${serviceName.replace(/-/g, "_")}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data:
`,
  };
}

function generateK8sDeployment(ir: ProjectIR): GeneratedFile {
  return {
    path: "k8s/deployment.yaml",
    category: "cloud",
    content: `# ${ir.projectName || ir.artifactId} — Kubernetes Deployment
# Auto-generated by Compleo Modernizer
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${ir.artifactId}
  labels:
    app: ${ir.artifactId}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${ir.artifactId}
  template:
    metadata:
      labels:
        app: ${ir.artifactId}
    spec:
      containers:
        - name: ${ir.artifactId}
          image: ${ir.artifactId}:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: ${ir.artifactId}-secrets
                  key: database-url
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
`,
  };
}

function generateK8sService(ir: ProjectIR): GeneratedFile {
  return {
    path: "k8s/service.yaml",
    category: "cloud",
    content: `# ${ir.projectName || ir.artifactId} — Kubernetes Service
# Auto-generated by Compleo Modernizer
apiVersion: v1
kind: Service
metadata:
  name: ${ir.artifactId}
spec:
  selector:
    app: ${ir.artifactId}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
`,
  };
}

// ─── POM.xml Generator ──────────────────────────────────────────────────────

function generatePomXml(ir: ProjectIR, basePackage: string): GeneratedFile {
  return {
    path: "pom.xml",
    category: "pom",
    content: `<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.2.5</version>
        <relativePath/>
    </parent>

    <groupId>${ir.groupId || "com.example"}</groupId>
    <artifactId>${ir.artifactId}</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <name>${ir.projectName || ir.artifactId}</name>
    <description>Modernized from EJB to Spring Boot 3.2 by Compleo Modernizer</description>

    <properties>
        <java.version>17</java.version>
    </properties>

    <dependencies>
        <!-- Spring Boot Starters -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>

        <!-- OpenAPI / Swagger -->
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
            <version>2.3.0</version>
        </dependency>

        <!-- Database -->
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
            <scope>runtime</scope>
        </dependency>

        <!-- Lombok -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>

        <!-- Test -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
`,
  };
}

// ─── Migration Report Generator ─────────────────────────────────────────────

function generateMigrationReport(
  ir: ProjectIR, domainMap: Map<string, UseCaseIR[]>, dtoMap: Map<string, DtoIR>,
  reportContext?: MigrationReportContext
): GeneratedFile {
  const now = new Date();
  const dateStr = now.toISOString().split("T")[0];
  const timeStr = now.toISOString().split("T")[1].substring(0, 5).replace(":", "h");

  // ─── Confidence score per UseCase ───
  function computeConfidence(uc: UseCaseIR): number {
    let score = 70; // base
    // VoIn/VoOut resolved
    if (uc.voInType && uc.voInType !== "Void") score += 8;
    if (uc.voOutType && uc.voOutType !== "Void") score += 8;
    // Has injected services
    if (uc.injectedServices.length > 0) score += 4;
    // Has transactional info
    if (uc.transactional) score += 5;
    // Has BIAN mapping
    if (uc.bianDomain && uc.bianAction) score += 5;
    return Math.min(score, 99);
  }

  const confidenceScores = ir.useCases.map(uc => computeConfidence(uc));
  const globalConfidence = confidenceScores.length > 0
    ? Math.round(confidenceScores.reduce((a, b) => a + b, 0) / confidenceScores.length)
    : 0;

  // ─── Section 1: Executive Summary ───
  const totalTests = [...domainMap.keys()].length * ir.useCases.length; // ~3 per endpoint
  const stubCount = ir.remoteInterfaces.length;
  const ambiguityTotal = reportContext?.ambiguities?.length || 0;
  const userResolved = reportContext?.userResolvedCount || 0;
  const autoResolved = reportContext?.autoResolvedCount || (ambiguityTotal - userResolved);

  // ─── Section 2: Mapping table with confidence ───
  let mappingTable = "| Classe source | Type | Endpoint genere | Methode | Confiance |\n";
  mappingTable += "|---------------|------|-----------------|---------|-----------|\n";
  for (let i = 0; i < ir.useCases.length; i++) {
    const uc = ir.useCases[i];
    const semantic = inferSemanticEndpoint(uc, uc.domain || "general");
    const conf = confidenceScores[i];
    mappingTable += `| ${uc.className} | UseCase | ${semantic.method} ${semantic.path} | ${toMethodName(uc.className)} | ${conf}% |\n`;
  }

  // ─── Section 3: User choices ───
  let choicesSection = "";
  if (reportContext?.ambiguities && reportContext.ambiguities.length > 0) {
    let choicesTable = "| Ambiguite | Classe concernee | Choix fait | Recommandation moteur |\n";
    choicesTable += "|-----------|-----------------|------------|----------------------|\n";
    for (const amb of reportContext.ambiguities) {
      const choice = reportContext.userChoices?.find(c => c.ambiguityId === amb.id);
      const selectedOption = choice
        ? amb.options.find(o => o.id === choice.selectedOptionId)
        : amb.options.find(o => o.label.includes("(recommande)") || o.id === "recommended");
      const selectedLabel = selectedOption?.label || "Auto (recommandation)";
      const isAligned = !choice || choice.selectedOptionId === amb.options[0]?.id;
      choicesTable += `| ${amb.type} | ${amb.affectedClass} | ${selectedLabel} | ${amb.recommendation} ${isAligned ? "(aligne)" : "(divergent)"} |\n`;
    }
    choicesSection = `\n## 3. Choix effectues par l'utilisateur\n\n${choicesTable}\n`;
  } else {
    choicesSection = `\n## 3. Choix effectues par l'utilisateur\n\nAucune ambiguite detectee — toutes les decisions ont ete prises automatiquement par le moteur.\n`;
  }

  // ─── Section 4: External dependencies ───
  let depsSection = "";
  if (ir.remoteInterfaces.length > 0) {
    let depsTable = "| Classe | Type | Stub genere | Action requise |\n";
    depsTable += "|--------|------|-------------|----------------|\n";
    for (const remote of ir.remoteInterfaces) {
      const adapterName = remote.className.replace("Remote", "Adapter");
      const methodNames = remote.methods.map(m => m.name).join(", ");
      depsTable += `| ${remote.className} | Service core banking | ${adapterName}.java | Implementer ${methodNames} |\n`;
    }
    depsSection = `\n## 4. Dependances externes non resolues\n\nCes composants n'etaient pas dans le ZIP et ont ete generes en tant que stubs a implementer :\n\n${depsTable}\n`;
  } else {
    depsSection = `\n## 4. Dependances externes non resolues\n\nAucune dependance externe detectee.\n`;
  }

  // ─── Section 5: Points d'attention ───
  const attentionPoints: string[] = [];
  // Divergent choices
  if (reportContext?.ambiguities && reportContext?.userChoices) {
    for (const choice of reportContext.userChoices) {
      const amb = reportContext.ambiguities.find(a => a.id === choice.ambiguityId);
      if (amb) {
        const recOption = amb.options[0]; // first option is usually the recommendation
        if (recOption && choice.selectedOptionId !== recOption.id) {
          attentionPoints.push(`L'URL choisie pour ${amb.affectedClass} diverge de la recommandation REST. Verifier avec votre architecte API.`);
        }
      }
    }
  }
  // Stubs
  for (const remote of ir.remoteInterfaces) {
    const adapterName = remote.className.replace("Remote", "Adapter");
    attentionPoints.push(`${adapterName} est un stub. L'appel au core banking doit etre implemente avant la mise en production.`);
  }
  // Warnings from IR
  for (const w of ir.warnings) {
    attentionPoints.push(w);
  }

  const attentionSection = attentionPoints.length > 0
    ? attentionPoints.map(p => `- ${p}`).join("\n")
    : "Aucun point d'attention.";

  // ─── Section: DTO Mapping ───
  let dtoTable = "| DTO Legacy | DTO Spring | Direction | Champs | Requis |\n";
  dtoTable += "|------------|------------|-----------|--------|--------|\n";
  for (const dto of ir.dtos) {
    const newName = mapDtoClassName(dto.className);
    const reqCount = dto.fields.filter(f => f.required).length;
    dtoTable += `| ${dto.className} | ${newName} | ${dto.direction} | ${dto.fields.length} | ${reqCount} |\n`;
  }

  // ─── Section: Files Generated ───
  const controllersCount = [...domainMap.keys()].length;
  const servicesCount = [...domainMap.keys()].length;
  const testsCount = [...domainMap.keys()].length;
  const totalFilesGenerated = ir.dtos.length + ir.enums.length + ir.exceptions.length + ir.validators.length + controllersCount * 3 + 8;

  return {
    path: "MIGRATION_REPORT.md",
    category: "report",
    content: `# Rapport de modernisation Compleo

Projet source : **${ir.projectName || ir.artifactId}** v${ir.version}
Genere le : ${dateStr} a ${timeStr}
Moteur Compleo : v2.0.0

---

## 1. Resume executif

| Metrique | Valeur |
|----------|--------|
| Classes EJB analysees | ${ir.stats.totalFiles} |
| UseCases detectes | ${ir.stats.useCaseCount} |
| DTOs detectes (VoIn/VoOut) | ${ir.stats.dtoCount} |
| Controllers REST generes | ${controllersCount} |
| Endpoints REST crees | ${ir.useCases.length} |
| Services generes | ${servicesCount} |
| Tests generes | ${ir.useCases.length * 3} (3 par endpoint) |
| Stubs crees (dependances externes) | ${stubCount}${ir.remoteInterfaces.length > 0 ? ` (${ir.remoteInterfaces.map(r => r.className.replace("Remote", "Adapter")).join(", ")})` : ""} |
| Score de confiance global | **${globalConfidence}%** |
| Ambiguites resolues par l'utilisateur | ${userResolved} |
| Ambiguites auto-resolues (recommandation) | ${autoResolved} |

---

## 2. Mapping complet EJB → REST

${mappingTable}

---
${choicesSection}
---
${depsSection}
---

## 5. Points d'attention

${attentionSection}

---

## 6. Prochaines etapes recommandees

1. ${ir.remoteInterfaces.length > 0 ? `Implementer ${ir.remoteInterfaces.map(r => r.className.replace("Remote", "Adapter")).join(", ")}` : "Implementer la logique metier dans les methodes Service (marquees TODO)"}
2. Configurer la datasource dans application.yml
3. ${attentionPoints.some(p => p.includes("diverge")) ? "Verifier les URLs divergentes avec votre equipe architecture" : "Verifier les endpoints REST avec votre equipe architecture"}
4. Executer les tests : \`mvn test\`
5. Demarrer l'application : \`mvn spring-boot:run\`
6. Acceder a Swagger UI : \`http://localhost:8080/swagger-ui.html\`

---

## Annexe A — Mapping DTO

${dtoTable}

## Annexe B — Domaines

${[...domainMap.entries()].map(([d, ucs]) => `- **${d}**: ${ucs.length} endpoint(s) — ${ucs.map(u => u.className).join(", ")}`).join("\n")}

## Annexe C — Regles qualite appliquees

| Regle | Description | Statut |
|-------|-------------|--------|
| R1 | Nommage semantique des endpoints | Appliquee |
| R2 | PathVariable vs RequestBody | Appliquee |
| R3 | Codes HTTP semantiques | Appliquee |
| R4 | Pas de try/catch dans les Controllers | Appliquee |
| R5 | Javadoc → @Operation OpenAPI | Appliquee |
| R6 | Injection par constructeur | Appliquee |
| R7 | @Transactional au bon niveau | Appliquee |
| R8 | Stub pour dependances externes | Appliquee |
| R9 | Types stricts, jamais Object | Appliquee |
| R10 | Bean Validation inferee | Appliquee |
| R11 | Donnees de test realistes | Appliquee |
| R12 | Minimum 3 tests par endpoint | Appliquee |

## Annexe D — Fichiers generes

| Categorie | Nombre |
|-----------|--------|
| Controllers | ${controllersCount} |
| Services | ${servicesCount} |
| DTOs | ${ir.dtos.length} |
| Tests | ${testsCount} |
| Enums | ${ir.enums.length} |
| Exceptions | ${ir.exceptions.length + 1} |
| Validators | ${ir.validators.length} |
| Config | 2 |
| Cloud | 4 |
| Total | ~${totalFilesGenerated} |

## Annexe E — Stack technique cible

| Legacy | Moderne |
|--------|--------|
| EJB 3.x | Spring Boot 3.2 |
| @UseCase + BaseUseCase | @RestController + @Service |
| ValueObject / VoIn / VoOut | Lombok @Data @Builder DTOs |
| JAXB @XmlElement | Jakarta Validation |
| @Transactional (JTA) | @Transactional (Spring) |
| FwkRollbackException | @RestControllerAdvice |
| EaiLog | Slf4j @Slf4j |
| Maven EJB Plugin | Spring Boot Maven Plugin |
| JUnit 4 | JUnit 5 + MockMvc |
| Injection manuelle | @RequiredArgsConstructor |
`,
  };
}

// ─── Step 4.2: Syntax Verification ─────────────────────────────────────────

export function verifySyntax(files: GeneratedFile[]): CompilationResult {
  const errors: CompilationError[] = [];
  const javaFiles = files.filter(f => f.path.endsWith(".java"));
  let passedFiles = 0;

  for (const file of javaFiles) {
    const fileErrors = verifyJavaFile(file);
    if (fileErrors.length === 0) {
      passedFiles++;
    } else {
      errors.push(...fileErrors);
    }
  }

  return {
    status: errors.some(e => e.severity === "error") ? "ERRORS" : errors.length > 0 ? "WARNINGS" : "OK",
    errors,
    checkedFiles: javaFiles.length,
    passedFiles,
  };
}

function verifyJavaFile(file: GeneratedFile): CompilationError[] {
  const errors: CompilationError[] = [];
  const lines = file.content.split("\n");
  const fileName = file.path.split("/").pop() || file.path;

  // 1. Check brace balance
  let braceCount = 0;
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    // Skip strings and comments
    const cleaned = line.replace(/"[^"]*"/g, "").replace(/\/\/.*$/, "");
    for (const ch of cleaned) {
      if (ch === "{") braceCount++;
      if (ch === "}") braceCount--;
    }
    if (braceCount < 0) {
      errors.push({ file: fileName, line: i + 1, column: 0, message: "Unexpected closing brace", severity: "error" });
    }
  }
  if (braceCount !== 0) {
    errors.push({ file: fileName, line: lines.length, column: 0, message: `Unbalanced braces: ${braceCount > 0 ? "missing" : "extra"} ${Math.abs(braceCount)} closing brace(s)`, severity: "error" });
  }

  // 2. Check package declaration
  if (!file.content.match(/^package\s+[\w.]+;/m) && file.path.endsWith(".java") && !file.path.includes("module-info")) {
    errors.push({ file: fileName, line: 1, column: 0, message: "Missing package declaration", severity: "error" });
  }

  // 3. Check for duplicate imports
  const importLines = lines.filter(l => l.trim().startsWith("import "));
  const importSet = new Set<string>();
  for (const imp of importLines) {
    const trimmed = imp.trim();
    if (importSet.has(trimmed)) {
      const lineNum = lines.indexOf(imp) + 1;
      errors.push({ file: fileName, line: lineNum, column: 0, message: `Duplicate import: ${trimmed}`, severity: "warning" });
    }
    importSet.add(trimmed);
  }

  // 4. Check for "Object" type usage (R9 violation)
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    // Skip comments and strings
    if (line.trim().startsWith("//") || line.trim().startsWith("*") || line.trim().startsWith("/*")) continue;
    // Check for standalone Object type (not in comments, not in generic bounds)
    if (/\bObject\b/.test(line) && !line.includes("@Override") && !line.includes("Object...") && !line.includes("ObjectMapper")) {
      // Only flag if it's a field or parameter type declaration
      if (/private\s+Object\s+/.test(line) || /public\s+Object\s+/.test(line) || /\(Object\s+/.test(line)) {
        errors.push({ file: fileName, line: i + 1, column: 0, message: "R9 violation: 'Object' type used — should be a specific type", severity: "warning" });
      }
    }
  }

  // 5. Check for missing semicolons on declarations
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();
    if (!line) continue;
    if (line.startsWith("//") || line.startsWith("*") || line.startsWith("/*") || line.startsWith("@") || line.startsWith("package") || line.startsWith("import")) continue;
    if (line.endsWith("{") || line.endsWith("}") || line.endsWith(",") || line.endsWith("(") || line.endsWith(")")) continue;
    // Field or variable declarations should end with ;
    if (/^(private|public|protected)\s+\w+\s+\w+\s*=/.test(line) && !line.endsWith(";")) {
      errors.push({ file: fileName, line: i + 1, column: line.length, message: "Missing semicolon", severity: "error" });
    }
  }

  return errors;
}

// ─── Utility Functions ──────────────────────────────────────────────────────

function toPascalCase(str: string): string {
  return str
    .split(/[-_\s]+/)
    .map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join("");
}

function toMethodName(className: string): string {
  const name = className.replace(/UC$/, "").replace(/UseCase$/, "");
  return name.charAt(0).toLowerCase() + name.slice(1);
}

function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

function mapDtoClassName(className: string): string {
  return className
    .replace(/VoIn$/, "RequestDTO")
    .replace(/VoOut$/, "ResponseDTO")
    .replace(/Dto$/, "DTO");
}
