CREATE TABLE `compleo_sessions` (
	`id` varchar(36) NOT NULL,
	`project_name` varchar(255) NOT NULL,
	`status` enum('uploaded','analyzed','waiting_choices','generated','error') NOT NULL DEFAULT 'uploaded',
	`files_data` json,
	`pom_xml` text,
	`bian_yml` text,
	`ir_data` json,
	`ambiguities_data` json,
	`user_choices_data` json,
	`resolved_ir_data` json,
	`generation_data` json,
	`zip_url` varchar(500),
	`pipeline_result_data` json,
	`detected_components_data` json,
	`multi_tech_generation_data` json,
	`maturity_score_data` json,
	`technologies_detected` json,
	`debug_events_data` json,
	`error_message` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `compleo_sessions_id` PRIMARY KEY(`id`)
);
