CREATE TABLE `agent_sessions` (
	`id` varchar(128) NOT NULL,
	`project_name` varchar(255) NOT NULL,
	`state` enum('IDLE','RUNNING','AWAITING_INPUT','COMPLETED','FAILED','CANCELLED') NOT NULL DEFAULT 'IDLE',
	`current_phase` varchar(50) NOT NULL DEFAULT 'IDLE',
	`config_data` json,
	`analysis_result_data` json,
	`ir_data` json,
	`pending_ambiguities_data` json,
	`user_choices_data` json,
	`generated_project_data` json,
	`compilation_result_data` json,
	`microservice_result_data` json,
	`saga_result_data` json,
	`migration_report` text,
	`enhanced_reports_data` json,
	`quality_score_data` json,
	`zip_url` varchar(500),
	`report_urls` json,
	`events_data` json,
	`pr_result_data` json,
	`error_message` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `agent_sessions_id` PRIMARY KEY(`id`)
);
