/**
 * Controller Generator — Generates Spring @RestController classes.
 * Rules: R1 (semantic naming), R2 (PathVariable), R3 (HTTP status), R4 (no try/catch), R5 (OpenAPI).
 * Extracted from spring-generator.ts (v5.5).
 */

import type { UseCaseIR, DtoIR } from "../java-parser";
import {
  type GeneratedFile,
  toPascalCase, toMethodName, mapDtoClassName, pluralize,
  inferSemanticEndpoint, detectIdParam, getIdParamName, getHttpAnnotation,
} from "./shared";

export function generateDomainController(
  basePackage: string, basePath: string, domain: string,
  useCases: UseCaseIR[], dtoMap: Map<string, DtoIR>
): GeneratedFile {
  const controllerName = toPascalCase(domain) + "Controller";
  const serviceName = toPascalCase(domain) + "Service";
  const serviceVar = domain + "Service";
  const imports = new Set<string>();
  imports.add("import lombok.RequiredArgsConstructor;");
  imports.add("import lombok.extern.slf4j.Slf4j;");
  imports.add("import org.springframework.http.ResponseEntity;");
  imports.add("import org.springframework.web.bind.annotation.*;");
  imports.add(`import ${basePackage}.service.${serviceName};`);
  imports.add("import io.swagger.v3.oas.annotations.Operation;");
  imports.add("import io.swagger.v3.oas.annotations.tags.Tag;");

  const endpoints: string[] = [];

  for (const uc of useCases) {
    const methodName = toMethodName(uc.className);
    const reqDto = dtoMap.get(uc.voInType);
    const resDto = dtoMap.get(uc.voOutType);

    const reqType = reqDto ? mapDtoClassName(reqDto.className) : null;
    const resType = resDto ? mapDtoClassName(resDto.className) : "Void";

    if (reqType) imports.add(`import ${basePackage}.dto.${reqType};`);
    if (resType !== "Void") imports.add(`import ${basePackage}.dto.${resType};`);
    if (reqType) imports.add("import jakarta.validation.Valid;");

    const semantic = inferSemanticEndpoint(uc, domain);
    const httpMethod = semantic.method;
    const controllerBasePath = `/api/v1/${pluralize(domain.toLowerCase())}`;
    let endpointPath = semantic.path.startsWith(controllerBasePath)
      ? semantic.path.substring(controllerBasePath.length)
      : semantic.subPath || "";

    const hasIdParam = detectIdParam(uc);
    const idParamName = hasIdParam ? getIdParamName(uc) : "";

    let paramList = "";
    if (hasIdParam && reqType) {
      paramList = `@PathVariable String ${idParamName}, @Valid @RequestBody ${reqType} request`;
    } else if (hasIdParam) {
      paramList = `@PathVariable String ${idParamName}`;
    } else if (reqType) {
      paramList = `@Valid @RequestBody ${reqType} request`;
    }

    const isCreation = httpMethod === "POST" && /^(creer|create|ajouter|add)/i.test(uc.className.replace(/UC$/, ""));
    let responseStatement: string;
    if (isCreation) {
      imports.add("import org.springframework.http.HttpStatus;");
      imports.add("import java.net.URI;");
      responseStatement = resType !== "Void"
        ? `        ${resType} result = ${serviceVar}.${methodName}(${reqType ? "request" : ""});\n        return ResponseEntity.status(HttpStatus.CREATED).body(result);`
        : `        ${serviceVar}.${methodName}(${reqType ? "request" : ""});\n        return ResponseEntity.status(HttpStatus.CREATED).build();`;
    } else {
      responseStatement = resType !== "Void"
        ? `        ${resType} result = ${serviceVar}.${methodName}(${reqType ? "request" : ""});\n        return ResponseEntity.ok(result);`
        : `        ${serviceVar}.${methodName}(${reqType ? "request" : ""});\n        return ResponseEntity.ok().build();`;
    }

    const javadoc = (uc as any).useCaseDescription || (uc as any).javadoc || "";
    const operationSummary = javadoc || `${methodName} — ${domain}`;

    const httpAnnotation = getHttpAnnotation(httpMethod, endpointPath || "/" + methodName.replace(/([a-z])([A-Z])/g, "$1-$2").toLowerCase());
    const returnGeneric = resType !== "Void" ? resType : "Void";

    endpoints.push(`
    /**
     * ${httpMethod} ${semantic.path}
     * ${uc.bianDomain ? `BIAN: ${uc.bianDomain} / ${uc.bianAction}` : `UseCase: ${uc.className}`}
     * ${javadoc ? javadoc : ""}
     */
    @Operation(summary = "${operationSummary}")
    ${httpAnnotation}
    public ResponseEntity<${returnGeneric}> ${methodName}(${paramList}) {
        log.info("${httpMethod} ${semantic.path}");
${responseStatement}
    }`);
  }

  const basePath2 = `/api/v1/${pluralize(domain.toLowerCase())}`;

  return {
    path: `${basePath}/controller/${controllerName}.java`,
    category: "controller",
    content: `package ${basePackage}.controller;

${[...imports].sort().join("\n")}

/**
 * ${controllerName} — REST API for ${domain} domain.
 * ${useCases.length} endpoint(s) migrated from EJB UseCases.
 * Auto-generated by Compleo Modernizer.
 */
@Slf4j
@RestController
@RequestMapping("${basePath2}")
@RequiredArgsConstructor
@Tag(name = "${toPascalCase(domain)}", description = "API for ${domain} operations")
public class ${controllerName} {

    private final ${serviceName} ${serviceVar};
${endpoints.join("\n")}
}
`,
  };
}
