/**
 * Model Generators — Enums, Exceptions, Validators.
 * Rules: R3 (semantic HTTP status codes), R4 (no try/catch in controllers).
 * Extracted from spring-generator.ts (v5.5).
 */

import type { EnumIR, ExceptionIR, ValidatorIR } from "../java-parser";
import type { GeneratedFile } from "./shared";

export function generateEnum(basePackage: string, basePath: string, en: EnumIR): GeneratedFile {
  const values = en.values.map(v => `    ${v}`).join(",\n");
  return {
    path: `${basePath}/enums/${en.className}.java`,
    category: "enum",
    content: `package ${basePackage}.enums;

/**
 * Enum ${en.className}.
 * Preserved from legacy project.
 */
public enum ${en.className} {
${values}
}
`,
  };
}

export function generateException(basePackage: string, basePath: string, ex: ExceptionIR): GeneratedFile {
  return {
    path: `${basePath}/exception/${ex.className}.java`,
    category: "exception",
    content: `package ${basePackage}.exception;

/**
 * ${ex.className} — Business exception.
 * Migrated from legacy ${ex.extendsClass}.
 */
public class ${ex.className} extends RuntimeException {

    public ${ex.className}() {
        super();
    }

    public ${ex.className}(String message) {
        super(message);
    }

    public ${ex.className}(String message, Throwable cause) {
        super(message, cause);
    }
}
`,
  };
}

export function generateGlobalExceptionHandler(basePackage: string, basePath: string, exceptions: ExceptionIR[]): GeneratedFile {
  const handlers = exceptions.map(ex => {
    const exName = ex.className.toLowerCase();
    let status = "HttpStatus.BAD_REQUEST";
    let statusCode = "400";
    if (exName.includes("notfound") || exName.includes("introuvable") || exName.includes("inexistant")) {
      status = "HttpStatus.NOT_FOUND";
      statusCode = "404";
    } else if (exName.includes("unauthorized") || exName.includes("nonautorise")) {
      status = "HttpStatus.UNAUTHORIZED";
      statusCode = "401";
    } else if (exName.includes("forbidden") || exName.includes("interdit")) {
      status = "HttpStatus.FORBIDDEN";
      statusCode = "403";
    } else if (exName.includes("validation") || exName.includes("regle") || exName.includes("metier")) {
      status = "HttpStatus.UNPROCESSABLE_ENTITY";
      statusCode = "422";
    }
    return `
    @ExceptionHandler(${ex.className}.class)
    public ResponseEntity<ErrorResponse> handle${ex.className}(${ex.className} ex) {
        log.warn("Business exception [${statusCode}]: {}", ex.getMessage());
        return ResponseEntity.status(${status})
            .body(new ErrorResponse("${ex.className.replace(/Exception$/, "").toUpperCase()}", ex.getMessage()));
    }`;
  }).join("\n");

  return {
    path: `${basePath}/exception/GlobalExceptionHandler.java`,
    category: "exception",
    content: `package ${basePackage}.exception;

import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.MethodArgumentNotValidException;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.RestControllerAdvice;

/**
 * Global exception handler — centralizes error responses.
 * R4: Controllers never catch exceptions; this handler does.
 * Auto-generated by Compleo Modernizer.
 */
@Slf4j
@RestControllerAdvice
public class GlobalExceptionHandler {

    public record ErrorResponse(String code, String message) {}
${handlers}

    @ExceptionHandler(MethodArgumentNotValidException.class)
    public ResponseEntity<ErrorResponse> handleValidation(MethodArgumentNotValidException ex) {
        String message = ex.getBindingResult().getFieldErrors().stream()
            .map(e -> e.getField() + ": " + e.getDefaultMessage())
            .reduce((a, b) -> a + "; " + b)
            .orElse("Validation failed");
        log.warn("Validation error: {}", message);
        return ResponseEntity.badRequest()
            .body(new ErrorResponse("VALIDATION_ERROR", message));
    }

    @ExceptionHandler(BusinessRuleException.class)
    public ResponseEntity<ErrorResponse> handleBusinessRule(BusinessRuleException ex) {
        log.warn("Business rule violation [422]: {}", ex.getMessage());
        return ResponseEntity.status(HttpStatus.UNPROCESSABLE_ENTITY)
            .body(new ErrorResponse("BUSINESS_RULE_VIOLATION", ex.getMessage()));
    }

    @ExceptionHandler(Exception.class)
    public ResponseEntity<ErrorResponse> handleGeneral(Exception ex) {
        log.error("Unexpected error", ex);
        return ResponseEntity.internalServerError()
            .body(new ErrorResponse("INTERNAL_ERROR", "An unexpected error occurred"));
    }
}
`,
  };
}

export function generateValidator(basePackage: string, basePath: string, val: ValidatorIR): GeneratedFile {
  if (val.className.endsWith("Validator")) {
    return {
      path: `${basePath}/validation/${val.className}.java`,
      category: "validator",
      content: `package ${basePackage}.validation;

import jakarta.validation.ConstraintValidator;
import jakarta.validation.ConstraintValidatorContext;

/**
 * ${val.className} — Custom validator for @${val.annotationName}.
 * Migrated from legacy project.
 */
public class ${val.className} implements ConstraintValidator<${val.annotationName}, String> {

    @Override
    public void initialize(${val.annotationName} constraintAnnotation) {
        // No-op
    }

    @Override
    public boolean isValid(String value, ConstraintValidatorContext context) {
        if (value == null || value.isBlank()) return true;
        // TODO: Implement validation logic from legacy code
        return value.length() >= 10;
    }
}
`,
    };
  }

  return {
    path: `${basePath}/validation/${val.className}.java`,
    category: "validator",
    content: `package ${basePackage}.validation;

import jakarta.validation.Constraint;
import jakarta.validation.Payload;
import java.lang.annotation.*;

/**
 * @${val.className} — Custom validation annotation.
 * Migrated from legacy project.
 */
@Documented
@Constraint(validatedBy = ${val.className.replace("Valid", "")}Validator.class)
@Target({ElementType.FIELD, ElementType.PARAMETER})
@Retention(RetentionPolicy.RUNTIME)
public @interface ${val.className} {
    String message() default "Invalid value";
    Class<?>[] groups() default {};
    Class<? extends Payload>[] payload() default {};
}
`,
  };
}
