-- ═══════════════════════════════════════════════════════════
-- Schéma SQL bancaire BMCE/BOA — Tables de référence
-- Pour validation de la génération Spring Boot par Compleo
-- ═══════════════════════════════════════════════════════════

-- Table Clients
CREATE TABLE T_CLIENTS (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    CIN VARCHAR(20) NOT NULL UNIQUE,
    NOM VARCHAR(100) NOT NULL,
    PRENOM VARCHAR(100) NOT NULL,
    DATE_NAISSANCE DATE NOT NULL,
    NATIONALITE VARCHAR(50) DEFAULT 'MAROCAINE',
    ADRESSE_EMAIL VARCHAR(255),
    TELEPHONE VARCHAR(20),
    ADRESSE_POSTALE VARCHAR(500),
    SITUATION_FAMILIALE VARCHAR(30),
    ACTIVITE_PROFESSIONNELLE VARCHAR(100),
    REVENU_MENSUEL DECIMAL(15,2),
    STATUT_KYC VARCHAR(20) DEFAULT 'EN_ATTENTE',
    SCORE_RISQUE INT DEFAULT 0,
    DATE_CREATION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATE_MODIFICATION TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Table Comptes
CREATE TABLE T_COMPTES (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NUM_COMPTE VARCHAR(24) NOT NULL UNIQUE,
    RIB_COMPLET VARCHAR(24) NOT NULL,
    IBAN VARCHAR(34),
    CLIENT_ID BIGINT NOT NULL,
    TYPE VARCHAR(20) NOT NULL COMMENT 'COURANT, EPARGNE, DEPOT_TERME, PROFESSIONNEL',
    STATUT VARCHAR(20) NOT NULL DEFAULT 'ACTIF' COMMENT 'ACTIF, BLOQUE, CLOTURE, DORMANT',
    DEVISE VARCHAR(3) DEFAULT 'MAD',
    SOLDE_DISPONIBLE DECIMAL(18,2) DEFAULT 0.00,
    SOLDE_COMPTABLE DECIMAL(18,2) DEFAULT 0.00,
    SOLDE_BLOQUE DECIMAL(18,2) DEFAULT 0.00,
    AGENCE_CODE VARCHAR(10) NOT NULL,
    DATE_OUVERTURE DATE NOT NULL,
    DATE_CLOTURE DATE,
    CONSTRAINT FK_COMPTES_CLIENT FOREIGN KEY (CLIENT_ID) REFERENCES T_CLIENTS(ID)
);

-- Table Opérations
CREATE TABLE T_OPERATIONS (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    REFERENCE_OPE VARCHAR(50) NOT NULL UNIQUE,
    NUM_COMPTE VARCHAR(24) NOT NULL,
    DATE_OPERATION TIMESTAMP NOT NULL,
    DATE_VALEUR DATE,
    LIBELLE VARCHAR(255),
    MONTANT DECIMAL(18,2) NOT NULL,
    SENS CHAR(1) NOT NULL COMMENT 'D=Débit, C=Crédit',
    SOLDE_APRES DECIMAL(18,2),
    TYPE_OPERATION VARCHAR(30),
    REFERENCE_EXTERNE VARCHAR(100),
    CONSTRAINT FK_OPERATIONS_COMPTE FOREIGN KEY (NUM_COMPTE) REFERENCES T_COMPTES(NUM_COMPTE)
);

-- Table Virements
CREATE TABLE T_VIREMENTS (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    REFERENCE_VIREMENT VARCHAR(50) NOT NULL UNIQUE,
    COMPTE_DEBITEUR VARCHAR(24) NOT NULL,
    IBAN_DESTINATAIRE VARCHAR(34),
    CODE_SWIFT VARCHAR(11),
    NOM_BENEFICIAIRE VARCHAR(200),
    ADRESSE_BENEFICIAIRE VARCHAR(500),
    MONTANT DECIMAL(18,2) NOT NULL,
    DEVISE_SOURCE VARCHAR(3) DEFAULT 'MAD',
    DEVISE_DESTINATION VARCHAR(3),
    TAUX_CHANGE DECIMAL(12,6),
    MONTANT_CONVERTI DECIMAL(18,2),
    FRAIS DECIMAL(18,2) DEFAULT 0.00,
    TYPE_VIREMENT VARCHAR(20) NOT NULL COMMENT 'NATIONAL, INTERNATIONAL, INSTANTANE',
    STATUT VARCHAR(20) NOT NULL DEFAULT 'EN_ATTENTE',
    MOTIF VARCHAR(500),
    DATE_CREATION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATE_EXECUTION TIMESTAMP,
    DATE_VALEUR DATE,
    CONSTRAINT FK_VIREMENTS_COMPTE FOREIGN KEY (COMPTE_DEBITEUR) REFERENCES T_COMPTES(NUM_COMPTE)
);

-- Table Cartes
CREATE TABLE T_CARTES (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NUM_CARTE VARCHAR(19) NOT NULL UNIQUE,
    NUM_COMPTE VARCHAR(24) NOT NULL,
    CLIENT_ID BIGINT NOT NULL,
    TYPE_CARTE VARCHAR(20) COMMENT 'VISA_CLASSIC, VISA_GOLD, MASTERCARD, ELECTRON',
    STATUT VARCHAR(20) DEFAULT 'ACTIVE' COMMENT 'ACTIVE, DESACTIVEE, OPPOSEE, EXPIREE',
    DATE_EMISSION DATE NOT NULL,
    DATE_EXPIRATION DATE NOT NULL,
    PLAFOND_JOURNALIER DECIMAL(18,2) DEFAULT 5000.00,
    PLAFOND_MENSUEL DECIMAL(18,2) DEFAULT 30000.00,
    PIN_HASH VARCHAR(256),
    DERNIERE_UTILISATION TIMESTAMP,
    CONSTRAINT FK_CARTES_COMPTE FOREIGN KEY (NUM_COMPTE) REFERENCES T_COMPTES(NUM_COMPTE),
    CONSTRAINT FK_CARTES_CLIENT FOREIGN KEY (CLIENT_ID) REFERENCES T_CLIENTS(ID)
);

-- Table Dossiers Crédit
CREATE TABLE T_DOSSIERS_CREDIT (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    REFERENCE_DOSSIER VARCHAR(50) NOT NULL UNIQUE,
    CLIENT_ID BIGINT NOT NULL,
    TYPE_CREDIT VARCHAR(20) NOT NULL COMMENT 'ACQUISITION, CONSTRUCTION, TERRAIN, RENOVATION',
    MONTANT DECIMAL(18,2) NOT NULL,
    APPORT_PERSONNEL DECIMAL(18,2) DEFAULT 0.00,
    DUREE_ANS INT NOT NULL,
    TAUX_PROPOSE DECIMAL(6,4),
    TAUX_NEGOCIE DECIMAL(6,4),
    TEG DECIMAL(6,4),
    MENSUALITE DECIMAL(18,2),
    STATUT VARCHAR(20) DEFAULT 'SOUMIS',
    SCORING_PRELIM INT,
    DATE_CREATION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATE_DECISION TIMESTAMP,
    CONSTRAINT FK_CREDIT_CLIENT FOREIGN KEY (CLIENT_ID) REFERENCES T_CLIENTS(ID)
);

-- Table Audit Trail
CREATE TABLE T_AUDIT (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    UTILISATEUR VARCHAR(100),
    ACTION VARCHAR(100) NOT NULL,
    ENTITE VARCHAR(100),
    ENTITE_ID VARCHAR(100),
    DETAILS TEXT,
    ADRESSE_IP VARCHAR(45),
    DATE_ACTION TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table Intérêts (batch)
CREATE TABLE T_INTERETS (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NUM_COMPTE VARCHAR(24) NOT NULL,
    MONTANT_INTERET DECIMAL(18,4) NOT NULL,
    TAUX DECIMAL(6,4) NOT NULL,
    DATE_DEBUT DATE NOT NULL,
    DATE_FIN DATE NOT NULL,
    JOURS INT NOT NULL,
    DATE_CALCUL TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_INTERETS_COMPTE FOREIGN KEY (NUM_COMPTE) REFERENCES T_COMPTES(NUM_COMPTE)
);

-- Index pour performances
CREATE INDEX IDX_COMPTES_CLIENT ON T_COMPTES(CLIENT_ID);
CREATE INDEX IDX_COMPTES_STATUT ON T_COMPTES(STATUT);
CREATE INDEX IDX_COMPTES_TYPE ON T_COMPTES(TYPE);
CREATE INDEX IDX_OPERATIONS_COMPTE ON T_OPERATIONS(NUM_COMPTE);
CREATE INDEX IDX_OPERATIONS_DATE ON T_OPERATIONS(DATE_OPERATION);
CREATE INDEX IDX_VIREMENTS_STATUT ON T_VIREMENTS(STATUT);
CREATE INDEX IDX_VIREMENTS_DATE ON T_VIREMENTS(DATE_EXECUTION);
CREATE INDEX IDX_CARTES_COMPTE ON T_CARTES(NUM_COMPTE);
CREATE INDEX IDX_AUDIT_DATE ON T_AUDIT(DATE_ACTION);
CREATE INDEX IDX_AUDIT_ENTITE ON T_AUDIT(ENTITE, ENTITE_ID);
